<?php

namespace CommonBundle\Repository;


use CommonBundle\Entity\Adm1;

/**
 * Adm1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Adm1Repository extends AdmBaseRepository
{
    public function findByCountry(string $iso3): array
    {
        return $this->findBy(['countryISO3' => $iso3], ['name' => 'ASC']);
    }

    /**
     * @param string $countryIso3Code
     * @param string $code
     *
     * @return Adm1|null
     */
    public function findByIsoAndCode(string $countryIso3Code, string $code): ?Adm1
    {
        return $this->findOneBy(['countryISO3' => $countryIso3Code, 'code' => $code]);
    }

}
