<?php

namespace CommonBundle\Repository;

/**
 * Adm1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Adm1Repository extends \Doctrine\ORM\EntityRepository
{
}
