<?php
/**
 * CampAddressAllOfTest
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  Humansis\WebApi\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Humansis Web App
 *
 * This is an API documentation for Humansis Web App.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace Humansis\WebApi\Model;

use PHPUnit\Framework\TestCase;

/**
 * CampAddressAllOfTest Class Doc Comment
 *
 * @category    Class */
// * @description CampAddressAllOf
/**
 * @package     Humansis\WebApi\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 */
class CampAddressAllOfTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CampAddressAllOf"
     */
    public function testCampAddressAllOf()
    {
        $testCampAddressAllOf = new CampAddressAllOf();
    }

    /**
     * Test attribute "tentNumber"
     */
    public function testPropertyTentNumber()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }
}
