<?php
/**
 * CodeListTest
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  Humansis\WebApi\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Humansis Web App
 *
 * This is an API documentation for Humansis Web App.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace Humansis\WebApi\Model;

use PHPUnit\Framework\TestCase;

/**
 * CodeListTest Class Doc Comment
 *
 * @category    Class */
// * @description CodeList
/**
 * @package     Humansis\WebApi\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 */
class CodeListTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CodeList"
     */
    public function testCodeList()
    {
        $testCodeList = new CodeList();
    }

    /**
     * Test attribute "totalCount"
     */
    public function testPropertyTotalCount()
    {
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
    }
}
