<?php
/**
 * ProjectTest
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  Humansis\WebApi\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Humansis Web App
 *
 * This is an API documentation for Humansis Web App.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace Humansis\WebApi\Model;

use PHPUnit\Framework\TestCase;

/**
 * ProjectTest Class Doc Comment
 *
 * @category    Class */
// * @description Project
/**
 * @package     Humansis\WebApi\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 */
class ProjectTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Project"
     */
    public function testProject()
    {
        $testProject = new Project();
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "iso3"
     */
    public function testPropertyIso3()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "internalId"
     */
    public function testPropertyInternalId()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "target"
     */
    public function testPropertyTarget()
    {
    }

    /**
     * Test attribute "numberOfHouseholds"
     */
    public function testPropertyNumberOfHouseholds()
    {
    }

    /**
     * Test attribute "startDate"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "endDate"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "sectors"
     */
    public function testPropertySectors()
    {
    }

    /**
     * Test attribute "donorIds"
     */
    public function testPropertyDonorIds()
    {
    }

    /**
     * Test attribute "deletable"
     */
    public function testPropertyDeletable()
    {
    }

    /**
     * Test attribute "beneficiariesReached"
     */
    public function testPropertyBeneficiariesReached()
    {
    }

    /**
     * Test attribute "projectInvoiceAddressLocal"
     */
    public function testPropertyProjectInvoiceAddressLocal()
    {
    }

    /**
     * Test attribute "projectInvoiceAddressEnglish"
     */
    public function testPropertyProjectInvoiceAddressEnglish()
    {
    }

    /**
     * Test attribute "allowedProductCategoryTypes"
     */
    public function testPropertyAllowedProductCategoryTypes()
    {
    }
}
