<?php
/**
 * SyncTest
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  Humansis\WebApi\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Humansis Web App
 *
 * This is an API documentation for Humansis Web App.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace Humansis\WebApi\Model;

use PHPUnit\Framework\TestCase;

/**
 * SyncTest Class Doc Comment
 *
 * @category    Class */
// * @description Sync
/**
 * @package     Humansis\WebApi\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 */
class SyncTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Sync"
     */
    public function testSync()
    {
        $testSync = new Sync();
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "createdBy"
     */
    public function testPropertyCreatedBy()
    {
    }

    /**
     * Test attribute "vendorId"
     */
    public function testPropertyVendorId()
    {
    }

    /**
     * Test attribute "validatedAt"
     */
    public function testPropertyValidatedAt()
    {
    }

    /**
     * Test attribute "rawData"
     */
    public function testPropertyRawData()
    {
    }

    /**
     * Test attribute "violations"
     */
    public function testPropertyViolations()
    {
    }
}
