<?php
/**
 * VendorTest
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  Humansis\WebApi\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Humansis Web App
 *
 * This is an API documentation for Humansis Web App.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace Humansis\WebApi\Model;

use PHPUnit\Framework\TestCase;

/**
 * VendorTest Class Doc Comment
 *
 * @category    Class */
// * @description Vendor
/**
 * @package     Humansis\WebApi\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 */
class VendorTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Vendor"
     */
    public function testVendor()
    {
        $testVendor = new Vendor();
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "shop"
     */
    public function testPropertyShop()
    {
    }

    /**
     * Test attribute "addressStreet"
     */
    public function testPropertyAddressStreet()
    {
    }

    /**
     * Test attribute "addressNumber"
     */
    public function testPropertyAddressNumber()
    {
    }

    /**
     * Test attribute "addressPostcode"
     */
    public function testPropertyAddressPostcode()
    {
    }

    /**
     * Test attribute "locationId"
     */
    public function testPropertyLocationId()
    {
    }

    /**
     * Test attribute "userId"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "adm1Id"
     */
    public function testPropertyAdm1Id()
    {
    }

    /**
     * Test attribute "adm2Id"
     */
    public function testPropertyAdm2Id()
    {
    }

    /**
     * Test attribute "adm3Id"
     */
    public function testPropertyAdm3Id()
    {
    }

    /**
     * Test attribute "adm4Id"
     */
    public function testPropertyAdm4Id()
    {
    }

    /**
     * Test attribute "vendorNo"
     */
    public function testPropertyVendorNo()
    {
    }

    /**
     * Test attribute "contractNo"
     */
    public function testPropertyContractNo()
    {
    }

    /**
     * Test attribute "canSellFood"
     */
    public function testPropertyCanSellFood()
    {
    }

    /**
     * Test attribute "canSellNonFood"
     */
    public function testPropertyCanSellNonFood()
    {
    }

    /**
     * Test attribute "canSellCashback"
     */
    public function testPropertyCanSellCashback()
    {
    }

    /**
     * Test attribute "canDoRemoteDistributions"
     */
    public function testPropertyCanDoRemoteDistributions()
    {
    }
}
