<?php
/**
 * Address
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  Humansis\WebApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Humansis Web App
 *
 * This is an API documentation for Humansis Web App.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace Humansis\WebApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Address model.
 *
 * @package Humansis\WebApi\Model
 * @author  OpenAPI Generator team
 */
class Address 
{
        /**
     * @var string
     * @SerializedName("type")
     * @Assert\NotNull()
     * @Assert\Choice({ "temporary_settlement" })
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $type;

    /**
     * Primary identifier
     *
     * @var int|null
     * @SerializedName("id")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $id;

    /**
     * @var string|null
     * @SerializedName("number")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 45
     * )
     */
    protected $number;

    /**
     * @var string|null
     * @SerializedName("street")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 45
     * )
     */
    protected $street;

    /**
     * @var string|null
     * @SerializedName("postcode")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 45
     * )
     */
    protected $postcode;

    /**
     * @var int|null
     * @SerializedName("locationId")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $locationId;

    /**
     * @var int|null
     * @SerializedName("adm1Id")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $adm1Id;

    /**
     * @var int|null
     * @SerializedName("adm2Id")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $adm2Id;

    /**
     * @var int|null
     * @SerializedName("adm3Id")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $adm3Id;

    /**
     * @var int|null
     * @SerializedName("adm4Id")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $adm4Id;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->type = isset($data['type']) ? $data['type'] : null;
        $this->id = isset($data['id']) ? $data['id'] : null;
        $this->number = isset($data['number']) ? $data['number'] : null;
        $this->street = isset($data['street']) ? $data['street'] : null;
        $this->postcode = isset($data['postcode']) ? $data['postcode'] : null;
        $this->locationId = isset($data['locationId']) ? $data['locationId'] : null;
        $this->adm1Id = isset($data['adm1Id']) ? $data['adm1Id'] : null;
        $this->adm2Id = isset($data['adm2Id']) ? $data['adm2Id'] : null;
        $this->adm3Id = isset($data['adm3Id']) ? $data['adm3Id'] : null;
        $this->adm4Id = isset($data['adm4Id']) ? $data['adm4Id'] : null;
    }

    /**
     * Gets type.
     *
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Sets type.
     *
     * @param string $type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Gets id.
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param int|null $id  Primary identifier
     *
     * @return $this
     */
    public function setId($id = null)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets number.
     *
     * @return string|null
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * Sets number.
     *
     * @param string|null $number
     *
     * @return $this
     */
    public function setNumber($number = null)
    {
        $this->number = $number;

        return $this;
    }

    /**
     * Gets street.
     *
     * @return string|null
     */
    public function getStreet()
    {
        return $this->street;
    }

    /**
     * Sets street.
     *
     * @param string|null $street
     *
     * @return $this
     */
    public function setStreet($street = null)
    {
        $this->street = $street;

        return $this;
    }

    /**
     * Gets postcode.
     *
     * @return string|null
     */
    public function getPostcode()
    {
        return $this->postcode;
    }

    /**
     * Sets postcode.
     *
     * @param string|null $postcode
     *
     * @return $this
     */
    public function setPostcode($postcode = null)
    {
        $this->postcode = $postcode;

        return $this;
    }

    /**
     * Gets locationId.
     *
     * @return int|null
     */
    public function getLocationId()
    {
        return $this->locationId;
    }

    /**
     * Sets locationId.
     *
     * @param int|null $locationId
     *
     * @return $this
     */
    public function setLocationId($locationId = null)
    {
        $this->locationId = $locationId;

        return $this;
    }

    /**
     * Gets adm1Id.
     *
     * @return int|null
     */
    public function getAdm1Id()
    {
        return $this->adm1Id;
    }

    /**
     * Sets adm1Id.
     *
     * @param int|null $adm1Id
     *
     * @return $this
     */
    public function setAdm1Id($adm1Id = null)
    {
        $this->adm1Id = $adm1Id;

        return $this;
    }

    /**
     * Gets adm2Id.
     *
     * @return int|null
     */
    public function getAdm2Id()
    {
        return $this->adm2Id;
    }

    /**
     * Sets adm2Id.
     *
     * @param int|null $adm2Id
     *
     * @return $this
     */
    public function setAdm2Id($adm2Id = null)
    {
        $this->adm2Id = $adm2Id;

        return $this;
    }

    /**
     * Gets adm3Id.
     *
     * @return int|null
     */
    public function getAdm3Id()
    {
        return $this->adm3Id;
    }

    /**
     * Sets adm3Id.
     *
     * @param int|null $adm3Id
     *
     * @return $this
     */
    public function setAdm3Id($adm3Id = null)
    {
        $this->adm3Id = $adm3Id;

        return $this;
    }

    /**
     * Gets adm4Id.
     *
     * @return int|null
     */
    public function getAdm4Id()
    {
        return $this->adm4Id;
    }

    /**
     * Sets adm4Id.
     *
     * @param int|null $adm4Id
     *
     * @return $this
     */
    public function setAdm4Id($adm4Id = null)
    {
        $this->adm4Id = $adm4Id;

        return $this;
    }
}


