<?php
/**
 * Household
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  Humansis\WebApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Humansis Web App
 *
 * This is an API documentation for Humansis Web App.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace Humansis\WebApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Household model.
 *
 * @package Humansis\WebApi\Model
 * @author  OpenAPI Generator team
 */
class Household 
{
        /**
     * Primary identifier
     *
     * @var int|null
     * @SerializedName("id")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $id;

    /**
     * Unique ISO code of country
     *
     * @var string|null
     * @SerializedName("iso3")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 3
     * )
     */
    protected $iso3;

    /**
     * one of codes from code list /households/livelihoods
     *
     * @var string|null
     * @SerializedName("livelihood")
     * @Assert\Choice({ "daily_labour", "farming_argiculture", "firming_livestock", "government", "home_duties", "trading", "own_business", "textiles" })
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $livelihood;

    /**
     * one of codes from code list /households/assets
     *
     * @var string[]|null
     * @SerializedName("assets")
     * @Assert\All({
     *   @Assert\Choice({ "a_c", "agricultural_land", "car", "flatscreen_tv", "livestock", "motorbike", "washing_machine" })
     * })
     * @Assert\All({
     *   @Assert\Type("string")
     * })
     * @Type("array<string>")
     */
    protected $assets;

    /**
     * one of codes from code list /households/shelter-statuses
     *
     * @var string|null
     * @SerializedName("shelterStatus")
     * @Assert\Choice({ "value", "tent", "makeshift_shelter", "transitional_shelter", "house_good_condition", "house_severely_damage", "house_moderately_damage", "room_unfinished_building", "room_public_building", "other" })
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $shelterStatus;

    /**
     * @var int[]|null
     * @SerializedName("projectIds")
     * @Assert\All({
     *   @Assert\Type("int")
     * })
     * @Type("array<int>")
     */
    protected $projectIds;

    /**
     * @var string|null
     * @SerializedName("notes")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $notes;

    /**
     * @var string|null
     * @SerializedName("longitude")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $longitude;

    /**
     * @var string|null
     * @SerializedName("latitude")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $latitude;

    /**
     * ID of HHH beneficiary
     *
     * @var int|null
     * @SerializedName("householdHeadId")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $householdHeadId;

    /**
     * @var int[]|null
     * @SerializedName("beneficiaryIds")
     * @Assert\All({
     *   @Assert\Type("int")
     * })
     * @Type("array<int>")
     */
    protected $beneficiaryIds;

    /**
     * @var Humansis\WebApi\Model\Beneficiary[]|null
     * @SerializedName("beneficiaries")
     * @Assert\All({
     *   @Assert\Type("Humansis\WebApi\Model\Beneficiary")
     * })
     * @Type("array<Humansis\WebApi\Model\Beneficiary>")
     */
    protected $beneficiaries;

    /**
     * @var int|null
     * @SerializedName("incomeLevel")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $incomeLevel;

    /**
     * @var int|null
     * @SerializedName("foodConsumptionScore")
     * @Assert\Type("int")
     * @Type("int")
     * @Assert\GreaterThan(1)
     * @Assert\LessThanOrEqual(1)
     */
    protected $foodConsumptionScore;

    /**
     * @var int|null
     * @SerializedName("copingStrategiesIndex")
     * @Assert\Type("int")
     * @Type("int")
     * @Assert\GreaterThan(1)
     * @Assert\LessThanOrEqual(1)
     */
    protected $copingStrategiesIndex;

    /**
     * @var int|null
     * @SerializedName("debtLevel")
     * @Assert\Type("int")
     * @Type("int")
     * @Assert\GreaterThan(1)
     * @Assert\LessThanOrEqual(1)
     */
    protected $debtLevel;

    /**
     * @var string|null
     * @SerializedName("supportDateReceived")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $supportDateReceived;

    /**
     * @var int[]|null
     * @SerializedName("supportReceivedTypes")
     * @Assert\All({
     *   @Assert\Type("int")
     * })
     * @Type("array<int>")
     */
    protected $supportReceivedTypes;

    /**
     * @var string|null
     * @SerializedName("supportOrganizationName")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $supportOrganizationName;

    /**
     * @var int|null
     * @SerializedName("incomeSpentOnFood")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $incomeSpentOnFood;

    /**
     * @var int|null
     * @SerializedName("houseIncome")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $houseIncome;

    /**
     * @var int[]|null
     * @SerializedName("countrySpecificAnswerIds")
     * @Assert\All({
     *   @Assert\Type("int")
     * })
     * @Type("array<int>")
     */
    protected $countrySpecificAnswerIds;

    /**
     * @var Humansis\WebApi\Model\CountrySpecificAnswer[]|null
     * @SerializedName("countrySpecificAnswers")
     * @Assert\All({
     *   @Assert\Type("Humansis\WebApi\Model\CountrySpecificAnswer")
     * })
     * @Type("array<Humansis\WebApi\Model\CountrySpecificAnswer>")
     */
    protected $countrySpecificAnswers;

    /**
     * @var AnyType|null
     * @SerializedName("campAddress")
     * @Assert\Type("AnyType")
     * @Type("AnyType")
     */
    protected $campAddress;

    /**
     * ID of CampAddress
     *
     * @var int|null
     * @SerializedName("campAddressId")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $campAddressId;

    /**
     * @var AnyType|null
     * @SerializedName("residenceAddress")
     * @Assert\Type("AnyType")
     * @Type("AnyType")
     */
    protected $residenceAddress;

    /**
     * ID of ResidencyAddress
     *
     * @var int|null
     * @SerializedName("residenceAddressId")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $residenceAddressId;

    /**
     * @var AnyType|null
     * @SerializedName("temporarySettlementAddress")
     * @Assert\Type("AnyType")
     * @Type("AnyType")
     */
    protected $temporarySettlementAddress;

    /**
     * ID of TemporarySettlementAddress
     *
     * @var int|null
     * @SerializedName("temporarySettlementAddressId")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $temporarySettlementAddressId;

    /**
     * Mandatory if any of proxy field is filled
     *
     * @var string|null
     * @SerializedName("proxyLocalFamilyName")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 255
     * )
     */
    protected $proxyLocalFamilyName;

    /**
     * Mandatory if any of proxy field is filled
     *
     * @var string|null
     * @SerializedName("proxyLocalGivenName")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 255
     * )
     */
    protected $proxyLocalGivenName;

    /**
     * @var string|null
     * @SerializedName("proxyLocalParentsName")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 255
     * )
     */
    protected $proxyLocalParentsName;

    /**
     * @var string|null
     * @SerializedName("proxyEnFamilyName")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 255
     * )
     */
    protected $proxyEnFamilyName;

    /**
     * @var string|null
     * @SerializedName("proxyEnGivenName")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 255
     * )
     */
    protected $proxyEnGivenName;

    /**
     * @var string|null
     * @SerializedName("proxyEnParentsName")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 255
     * )
     */
    protected $proxyEnParentsName;

    /**
     * @var NationalID|null
     * @SerializedName("proxyNationalIdCard")
     * @Assert\Type("NationalID")
     * @Type("NationalID")
     */
    protected $proxyNationalIdCard;

    /**
     * @var Phone|null
     * @SerializedName("proxyPhone")
     * @Assert\Type("Phone")
     * @Type("Phone")
     */
    protected $proxyPhone;

    /**
     * @var int|null
     * @SerializedName("proxyNationalIdCardId")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $proxyNationalIdCardId;

    /**
     * @var int|null
     * @SerializedName("proxyPhoneId")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $proxyPhoneId;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->id = isset($data['id']) ? $data['id'] : null;
        $this->iso3 = isset($data['iso3']) ? $data['iso3'] : null;
        $this->livelihood = isset($data['livelihood']) ? $data['livelihood'] : null;
        $this->assets = isset($data['assets']) ? $data['assets'] : null;
        $this->shelterStatus = isset($data['shelterStatus']) ? $data['shelterStatus'] : null;
        $this->projectIds = isset($data['projectIds']) ? $data['projectIds'] : null;
        $this->notes = isset($data['notes']) ? $data['notes'] : null;
        $this->longitude = isset($data['longitude']) ? $data['longitude'] : null;
        $this->latitude = isset($data['latitude']) ? $data['latitude'] : null;
        $this->householdHeadId = isset($data['householdHeadId']) ? $data['householdHeadId'] : null;
        $this->beneficiaryIds = isset($data['beneficiaryIds']) ? $data['beneficiaryIds'] : null;
        $this->beneficiaries = isset($data['beneficiaries']) ? $data['beneficiaries'] : null;
        $this->incomeLevel = isset($data['incomeLevel']) ? $data['incomeLevel'] : null;
        $this->foodConsumptionScore = isset($data['foodConsumptionScore']) ? $data['foodConsumptionScore'] : null;
        $this->copingStrategiesIndex = isset($data['copingStrategiesIndex']) ? $data['copingStrategiesIndex'] : null;
        $this->debtLevel = isset($data['debtLevel']) ? $data['debtLevel'] : null;
        $this->supportDateReceived = isset($data['supportDateReceived']) ? $data['supportDateReceived'] : null;
        $this->supportReceivedTypes = isset($data['supportReceivedTypes']) ? $data['supportReceivedTypes'] : null;
        $this->supportOrganizationName = isset($data['supportOrganizationName']) ? $data['supportOrganizationName'] : null;
        $this->incomeSpentOnFood = isset($data['incomeSpentOnFood']) ? $data['incomeSpentOnFood'] : null;
        $this->houseIncome = isset($data['houseIncome']) ? $data['houseIncome'] : null;
        $this->countrySpecificAnswerIds = isset($data['countrySpecificAnswerIds']) ? $data['countrySpecificAnswerIds'] : null;
        $this->countrySpecificAnswers = isset($data['countrySpecificAnswers']) ? $data['countrySpecificAnswers'] : null;
        $this->campAddress = isset($data['campAddress']) ? $data['campAddress'] : null;
        $this->campAddressId = isset($data['campAddressId']) ? $data['campAddressId'] : null;
        $this->residenceAddress = isset($data['residenceAddress']) ? $data['residenceAddress'] : null;
        $this->residenceAddressId = isset($data['residenceAddressId']) ? $data['residenceAddressId'] : null;
        $this->temporarySettlementAddress = isset($data['temporarySettlementAddress']) ? $data['temporarySettlementAddress'] : null;
        $this->temporarySettlementAddressId = isset($data['temporarySettlementAddressId']) ? $data['temporarySettlementAddressId'] : null;
        $this->proxyLocalFamilyName = isset($data['proxyLocalFamilyName']) ? $data['proxyLocalFamilyName'] : null;
        $this->proxyLocalGivenName = isset($data['proxyLocalGivenName']) ? $data['proxyLocalGivenName'] : null;
        $this->proxyLocalParentsName = isset($data['proxyLocalParentsName']) ? $data['proxyLocalParentsName'] : null;
        $this->proxyEnFamilyName = isset($data['proxyEnFamilyName']) ? $data['proxyEnFamilyName'] : null;
        $this->proxyEnGivenName = isset($data['proxyEnGivenName']) ? $data['proxyEnGivenName'] : null;
        $this->proxyEnParentsName = isset($data['proxyEnParentsName']) ? $data['proxyEnParentsName'] : null;
        $this->proxyNationalIdCard = isset($data['proxyNationalIdCard']) ? $data['proxyNationalIdCard'] : null;
        $this->proxyPhone = isset($data['proxyPhone']) ? $data['proxyPhone'] : null;
        $this->proxyNationalIdCardId = isset($data['proxyNationalIdCardId']) ? $data['proxyNationalIdCardId'] : null;
        $this->proxyPhoneId = isset($data['proxyPhoneId']) ? $data['proxyPhoneId'] : null;
    }

    /**
     * Gets id.
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param int|null $id  Primary identifier
     *
     * @return $this
     */
    public function setId($id = null)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets iso3.
     *
     * @return string|null
     */
    public function getIso3()
    {
        return $this->iso3;
    }

    /**
     * Sets iso3.
     *
     * @param string|null $iso3  Unique ISO code of country
     *
     * @return $this
     */
    public function setIso3($iso3 = null)
    {
        $this->iso3 = $iso3;

        return $this;
    }

    /**
     * Gets livelihood.
     *
     * @return string|null
     */
    public function getLivelihood()
    {
        return $this->livelihood;
    }

    /**
     * Sets livelihood.
     *
     * @param string|null $livelihood  one of codes from code list /households/livelihoods
     *
     * @return $this
     */
    public function setLivelihood($livelihood = null)
    {
        $this->livelihood = $livelihood;

        return $this;
    }

    /**
     * Gets assets.
     *
     * @return string[]|null
     */
    public function getAssets(): ?array
    {
        return $this->assets;
    }

    /**
     * Sets assets.
     *
     * @param string[]|null $assets  one of codes from code list /households/assets
     *
     * @return $this
     */
    public function setAssets(array $assets = null)
    {
        $this->assets = $assets;

        return $this;
    }

    /**
     * Gets shelterStatus.
     *
     * @return string|null
     */
    public function getShelterStatus()
    {
        return $this->shelterStatus;
    }

    /**
     * Sets shelterStatus.
     *
     * @param string|null $shelterStatus  one of codes from code list /households/shelter-statuses
     *
     * @return $this
     */
    public function setShelterStatus($shelterStatus = null)
    {
        $this->shelterStatus = $shelterStatus;

        return $this;
    }

    /**
     * Gets projectIds.
     *
     * @return int[]|null
     */
    public function getProjectIds(): ?array
    {
        return $this->projectIds;
    }

    /**
     * Sets projectIds.
     *
     * @param int[]|null $projectIds
     *
     * @return $this
     */
    public function setProjectIds(array $projectIds = null)
    {
        $this->projectIds = $projectIds;

        return $this;
    }

    /**
     * Gets notes.
     *
     * @return string|null
     */
    public function getNotes()
    {
        return $this->notes;
    }

    /**
     * Sets notes.
     *
     * @param string|null $notes
     *
     * @return $this
     */
    public function setNotes($notes = null)
    {
        $this->notes = $notes;

        return $this;
    }

    /**
     * Gets longitude.
     *
     * @return string|null
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * Sets longitude.
     *
     * @param string|null $longitude
     *
     * @return $this
     */
    public function setLongitude($longitude = null)
    {
        $this->longitude = $longitude;

        return $this;
    }

    /**
     * Gets latitude.
     *
     * @return string|null
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * Sets latitude.
     *
     * @param string|null $latitude
     *
     * @return $this
     */
    public function setLatitude($latitude = null)
    {
        $this->latitude = $latitude;

        return $this;
    }

    /**
     * Gets householdHeadId.
     *
     * @return int|null
     */
    public function getHouseholdHeadId()
    {
        return $this->householdHeadId;
    }

    /**
     * Sets householdHeadId.
     *
     * @param int|null $householdHeadId  ID of HHH beneficiary
     *
     * @return $this
     */
    public function setHouseholdHeadId($householdHeadId = null)
    {
        $this->householdHeadId = $householdHeadId;

        return $this;
    }

    /**
     * Gets beneficiaryIds.
     *
     * @return int[]|null
     */
    public function getBeneficiaryIds(): ?array
    {
        return $this->beneficiaryIds;
    }

    /**
     * Sets beneficiaryIds.
     *
     * @param int[]|null $beneficiaryIds
     *
     * @return $this
     */
    public function setBeneficiaryIds(array $beneficiaryIds = null)
    {
        $this->beneficiaryIds = $beneficiaryIds;

        return $this;
    }

    /**
     * Gets beneficiaries.
     *
     * @return Humansis\WebApi\Model\Beneficiary[]|null
     */
    public function getBeneficiaries(): ?array
    {
        return $this->beneficiaries;
    }

    /**
     * Sets beneficiaries.
     *
     * @param Humansis\WebApi\Model\Beneficiary[]|null $beneficiaries
     *
     * @return $this
     */
    public function setBeneficiaries(array $beneficiaries = null)
    {
        $this->beneficiaries = $beneficiaries;

        return $this;
    }

    /**
     * Gets incomeLevel.
     *
     * @return int|null
     */
    public function getIncomeLevel()
    {
        return $this->incomeLevel;
    }

    /**
     * Sets incomeLevel.
     *
     * @param int|null $incomeLevel
     *
     * @return $this
     */
    public function setIncomeLevel($incomeLevel = null)
    {
        $this->incomeLevel = $incomeLevel;

        return $this;
    }

    /**
     * Gets foodConsumptionScore.
     *
     * @return int|null
     */
    public function getFoodConsumptionScore()
    {
        return $this->foodConsumptionScore;
    }

    /**
     * Sets foodConsumptionScore.
     *
     * @param int|null $foodConsumptionScore
     *
     * @return $this
     */
    public function setFoodConsumptionScore($foodConsumptionScore = null)
    {
        $this->foodConsumptionScore = $foodConsumptionScore;

        return $this;
    }

    /**
     * Gets copingStrategiesIndex.
     *
     * @return int|null
     */
    public function getCopingStrategiesIndex()
    {
        return $this->copingStrategiesIndex;
    }

    /**
     * Sets copingStrategiesIndex.
     *
     * @param int|null $copingStrategiesIndex
     *
     * @return $this
     */
    public function setCopingStrategiesIndex($copingStrategiesIndex = null)
    {
        $this->copingStrategiesIndex = $copingStrategiesIndex;

        return $this;
    }

    /**
     * Gets debtLevel.
     *
     * @return int|null
     */
    public function getDebtLevel()
    {
        return $this->debtLevel;
    }

    /**
     * Sets debtLevel.
     *
     * @param int|null $debtLevel
     *
     * @return $this
     */
    public function setDebtLevel($debtLevel = null)
    {
        $this->debtLevel = $debtLevel;

        return $this;
    }

    /**
     * Gets supportDateReceived.
     *
     * @return string|null
     */
    public function getSupportDateReceived()
    {
        return $this->supportDateReceived;
    }

    /**
     * Sets supportDateReceived.
     *
     * @param string|null $supportDateReceived
     *
     * @return $this
     */
    public function setSupportDateReceived($supportDateReceived = null)
    {
        $this->supportDateReceived = $supportDateReceived;

        return $this;
    }

    /**
     * Gets supportReceivedTypes.
     *
     * @return int[]|null
     */
    public function getSupportReceivedTypes(): ?array
    {
        return $this->supportReceivedTypes;
    }

    /**
     * Sets supportReceivedTypes.
     *
     * @param int[]|null $supportReceivedTypes
     *
     * @return $this
     */
    public function setSupportReceivedTypes(array $supportReceivedTypes = null)
    {
        $this->supportReceivedTypes = $supportReceivedTypes;

        return $this;
    }

    /**
     * Gets supportOrganizationName.
     *
     * @return string|null
     */
    public function getSupportOrganizationName()
    {
        return $this->supportOrganizationName;
    }

    /**
     * Sets supportOrganizationName.
     *
     * @param string|null $supportOrganizationName
     *
     * @return $this
     */
    public function setSupportOrganizationName($supportOrganizationName = null)
    {
        $this->supportOrganizationName = $supportOrganizationName;

        return $this;
    }

    /**
     * Gets incomeSpentOnFood.
     *
     * @return int|null
     */
    public function getIncomeSpentOnFood()
    {
        return $this->incomeSpentOnFood;
    }

    /**
     * Sets incomeSpentOnFood.
     *
     * @param int|null $incomeSpentOnFood
     *
     * @return $this
     */
    public function setIncomeSpentOnFood($incomeSpentOnFood = null)
    {
        $this->incomeSpentOnFood = $incomeSpentOnFood;

        return $this;
    }

    /**
     * Gets houseIncome.
     *
     * @return int|null
     */
    public function getHouseIncome()
    {
        return $this->houseIncome;
    }

    /**
     * Sets houseIncome.
     *
     * @param int|null $houseIncome
     *
     * @return $this
     */
    public function setHouseIncome($houseIncome = null)
    {
        $this->houseIncome = $houseIncome;

        return $this;
    }

    /**
     * Gets countrySpecificAnswerIds.
     *
     * @return int[]|null
     */
    public function getCountrySpecificAnswerIds(): ?array
    {
        return $this->countrySpecificAnswerIds;
    }

    /**
     * Sets countrySpecificAnswerIds.
     *
     * @param int[]|null $countrySpecificAnswerIds
     *
     * @return $this
     */
    public function setCountrySpecificAnswerIds(array $countrySpecificAnswerIds = null)
    {
        $this->countrySpecificAnswerIds = $countrySpecificAnswerIds;

        return $this;
    }

    /**
     * Gets countrySpecificAnswers.
     *
     * @return Humansis\WebApi\Model\CountrySpecificAnswer[]|null
     */
    public function getCountrySpecificAnswers(): ?array
    {
        return $this->countrySpecificAnswers;
    }

    /**
     * Sets countrySpecificAnswers.
     *
     * @param Humansis\WebApi\Model\CountrySpecificAnswer[]|null $countrySpecificAnswers
     *
     * @return $this
     */
    public function setCountrySpecificAnswers(array $countrySpecificAnswers = null)
    {
        $this->countrySpecificAnswers = $countrySpecificAnswers;

        return $this;
    }

    /**
     * Gets campAddress.
     *
     * @return AnyType|null
     */
    public function getCampAddress()
    {
        return $this->campAddress;
    }

    /**
     * Sets campAddress.
     *
     * @param AnyType|null $campAddress
     *
     * @return $this
     */
    public function setCampAddress($campAddress = null)
    {
        $this->campAddress = $campAddress;

        return $this;
    }

    /**
     * Gets campAddressId.
     *
     * @return int|null
     */
    public function getCampAddressId()
    {
        return $this->campAddressId;
    }

    /**
     * Sets campAddressId.
     *
     * @param int|null $campAddressId  ID of CampAddress
     *
     * @return $this
     */
    public function setCampAddressId($campAddressId = null)
    {
        $this->campAddressId = $campAddressId;

        return $this;
    }

    /**
     * Gets residenceAddress.
     *
     * @return AnyType|null
     */
    public function getResidenceAddress()
    {
        return $this->residenceAddress;
    }

    /**
     * Sets residenceAddress.
     *
     * @param AnyType|null $residenceAddress
     *
     * @return $this
     */
    public function setResidenceAddress($residenceAddress = null)
    {
        $this->residenceAddress = $residenceAddress;

        return $this;
    }

    /**
     * Gets residenceAddressId.
     *
     * @return int|null
     */
    public function getResidenceAddressId()
    {
        return $this->residenceAddressId;
    }

    /**
     * Sets residenceAddressId.
     *
     * @param int|null $residenceAddressId  ID of ResidencyAddress
     *
     * @return $this
     */
    public function setResidenceAddressId($residenceAddressId = null)
    {
        $this->residenceAddressId = $residenceAddressId;

        return $this;
    }

    /**
     * Gets temporarySettlementAddress.
     *
     * @return AnyType|null
     */
    public function getTemporarySettlementAddress()
    {
        return $this->temporarySettlementAddress;
    }

    /**
     * Sets temporarySettlementAddress.
     *
     * @param AnyType|null $temporarySettlementAddress
     *
     * @return $this
     */
    public function setTemporarySettlementAddress($temporarySettlementAddress = null)
    {
        $this->temporarySettlementAddress = $temporarySettlementAddress;

        return $this;
    }

    /**
     * Gets temporarySettlementAddressId.
     *
     * @return int|null
     */
    public function getTemporarySettlementAddressId()
    {
        return $this->temporarySettlementAddressId;
    }

    /**
     * Sets temporarySettlementAddressId.
     *
     * @param int|null $temporarySettlementAddressId  ID of TemporarySettlementAddress
     *
     * @return $this
     */
    public function setTemporarySettlementAddressId($temporarySettlementAddressId = null)
    {
        $this->temporarySettlementAddressId = $temporarySettlementAddressId;

        return $this;
    }

    /**
     * Gets proxyLocalFamilyName.
     *
     * @return string|null
     */
    public function getProxyLocalFamilyName()
    {
        return $this->proxyLocalFamilyName;
    }

    /**
     * Sets proxyLocalFamilyName.
     *
     * @param string|null $proxyLocalFamilyName  Mandatory if any of proxy field is filled
     *
     * @return $this
     */
    public function setProxyLocalFamilyName($proxyLocalFamilyName = null)
    {
        $this->proxyLocalFamilyName = $proxyLocalFamilyName;

        return $this;
    }

    /**
     * Gets proxyLocalGivenName.
     *
     * @return string|null
     */
    public function getProxyLocalGivenName()
    {
        return $this->proxyLocalGivenName;
    }

    /**
     * Sets proxyLocalGivenName.
     *
     * @param string|null $proxyLocalGivenName  Mandatory if any of proxy field is filled
     *
     * @return $this
     */
    public function setProxyLocalGivenName($proxyLocalGivenName = null)
    {
        $this->proxyLocalGivenName = $proxyLocalGivenName;

        return $this;
    }

    /**
     * Gets proxyLocalParentsName.
     *
     * @return string|null
     */
    public function getProxyLocalParentsName()
    {
        return $this->proxyLocalParentsName;
    }

    /**
     * Sets proxyLocalParentsName.
     *
     * @param string|null $proxyLocalParentsName
     *
     * @return $this
     */
    public function setProxyLocalParentsName($proxyLocalParentsName = null)
    {
        $this->proxyLocalParentsName = $proxyLocalParentsName;

        return $this;
    }

    /**
     * Gets proxyEnFamilyName.
     *
     * @return string|null
     */
    public function getProxyEnFamilyName()
    {
        return $this->proxyEnFamilyName;
    }

    /**
     * Sets proxyEnFamilyName.
     *
     * @param string|null $proxyEnFamilyName
     *
     * @return $this
     */
    public function setProxyEnFamilyName($proxyEnFamilyName = null)
    {
        $this->proxyEnFamilyName = $proxyEnFamilyName;

        return $this;
    }

    /**
     * Gets proxyEnGivenName.
     *
     * @return string|null
     */
    public function getProxyEnGivenName()
    {
        return $this->proxyEnGivenName;
    }

    /**
     * Sets proxyEnGivenName.
     *
     * @param string|null $proxyEnGivenName
     *
     * @return $this
     */
    public function setProxyEnGivenName($proxyEnGivenName = null)
    {
        $this->proxyEnGivenName = $proxyEnGivenName;

        return $this;
    }

    /**
     * Gets proxyEnParentsName.
     *
     * @return string|null
     */
    public function getProxyEnParentsName()
    {
        return $this->proxyEnParentsName;
    }

    /**
     * Sets proxyEnParentsName.
     *
     * @param string|null $proxyEnParentsName
     *
     * @return $this
     */
    public function setProxyEnParentsName($proxyEnParentsName = null)
    {
        $this->proxyEnParentsName = $proxyEnParentsName;

        return $this;
    }

    /**
     * Gets proxyNationalIdCard.
     *
     * @return NationalID|null
     */
    public function getProxyNationalIdCard()
    {
        return $this->proxyNationalIdCard;
    }

    /**
     * Sets proxyNationalIdCard.
     *
     * @param NationalID|null $proxyNationalIdCard
     *
     * @return $this
     */
    public function setProxyNationalIdCard($proxyNationalIdCard = null)
    {
        $this->proxyNationalIdCard = $proxyNationalIdCard;

        return $this;
    }

    /**
     * Gets proxyPhone.
     *
     * @return Phone|null
     */
    public function getProxyPhone()
    {
        return $this->proxyPhone;
    }

    /**
     * Sets proxyPhone.
     *
     * @param Phone|null $proxyPhone
     *
     * @return $this
     */
    public function setProxyPhone($proxyPhone = null)
    {
        $this->proxyPhone = $proxyPhone;

        return $this;
    }

    /**
     * Gets proxyNationalIdCardId.
     *
     * @return int|null
     */
    public function getProxyNationalIdCardId()
    {
        return $this->proxyNationalIdCardId;
    }

    /**
     * Sets proxyNationalIdCardId.
     *
     * @param int|null $proxyNationalIdCardId
     *
     * @return $this
     */
    public function setProxyNationalIdCardId($proxyNationalIdCardId = null)
    {
        $this->proxyNationalIdCardId = $proxyNationalIdCardId;

        return $this;
    }

    /**
     * Gets proxyPhoneId.
     *
     * @return int|null
     */
    public function getProxyPhoneId()
    {
        return $this->proxyPhoneId;
    }

    /**
     * Sets proxyPhoneId.
     *
     * @param int|null $proxyPhoneId
     *
     * @return $this
     */
    public function setProxyPhoneId($proxyPhoneId = null)
    {
        $this->proxyPhoneId = $proxyPhoneId;

        return $this;
    }
}


