<?php
/**
 * InlineObject4
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  Humansis\WebApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Humansis Web App
 *
 * This is an API documentation for Humansis Web App.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace Humansis\WebApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the InlineObject4 model.
 *
 * @package Humansis\WebApi\Model
 * @author  OpenAPI Generator team
 */
class InlineObject4 
{
        /**
     * @var bool|null
     * @SerializedName("2fa")
     * @Assert\Type("bool")
     * @Type("bool")
     */
    protected $_2fa;

    /**
     * @var string|null
     * @SerializedName("phoneNumber")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $phoneNumber;

    /**
     * @var string|null
     * @SerializedName("phonePrefix")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $phonePrefix;

    /**
     * hashed password
     *
     * @var string|null
     * @SerializedName("password")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $password;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->_2fa = isset($data['_2fa']) ? $data['_2fa'] : null;
        $this->phoneNumber = isset($data['phoneNumber']) ? $data['phoneNumber'] : null;
        $this->phonePrefix = isset($data['phonePrefix']) ? $data['phonePrefix'] : null;
        $this->password = isset($data['password']) ? $data['password'] : null;
    }

    /**
     * Gets _2fa.
     *
     * @return bool|null
     */
    public function is2fa()
    {
        return $this->_2fa;
    }

    /**
     * Sets _2fa.
     *
     * @param bool|null $_2fa
     *
     * @return $this
     */
    public function set2fa($_2fa = null)
    {
        $this->_2fa = $_2fa;

        return $this;
    }

    /**
     * Gets phoneNumber.
     *
     * @return string|null
     */
    public function getPhoneNumber()
    {
        return $this->phoneNumber;
    }

    /**
     * Sets phoneNumber.
     *
     * @param string|null $phoneNumber
     *
     * @return $this
     */
    public function setPhoneNumber($phoneNumber = null)
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    /**
     * Gets phonePrefix.
     *
     * @return string|null
     */
    public function getPhonePrefix()
    {
        return $this->phonePrefix;
    }

    /**
     * Sets phonePrefix.
     *
     * @param string|null $phonePrefix
     *
     * @return $this
     */
    public function setPhonePrefix($phonePrefix = null)
    {
        $this->phonePrefix = $phonePrefix;

        return $this;
    }

    /**
     * Gets password.
     *
     * @return string|null
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Sets password.
     *
     * @param string|null $password  hashed password
     *
     * @return $this
     */
    public function setPassword($password = null)
    {
        $this->password = $password;

        return $this;
    }
}


