<?php
/**
 * InlineObject1
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  Humansis\WebApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Humansis Web App
 *
 * This is an API documentation for Humansis Web App.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace Humansis\WebApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the InlineObject1 model.
 *
 * @package Humansis\WebApi\Model
 * @author  OpenAPI Generator team
 */
class InlineObject1 
{
        /**
     * @var string|null
     * @SerializedName("status")
     * @Assert\Choice({ "To Create", "To Update", "To Link", "To Ignore" })
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $status;

    /**
     * @var int|null
     * @SerializedName("acceptedDuplicityId")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $acceptedDuplicityId;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->status = isset($data['status']) ? $data['status'] : null;
        $this->acceptedDuplicityId = isset($data['acceptedDuplicityId']) ? $data['acceptedDuplicityId'] : null;
    }

    /**
     * Gets status.
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Sets status.
     *
     * @param string|null $status
     *
     * @return $this
     */
    public function setStatus($status = null)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Gets acceptedDuplicityId.
     *
     * @return int|null
     */
    public function getAcceptedDuplicityId()
    {
        return $this->acceptedDuplicityId;
    }

    /**
     * Sets acceptedDuplicityId.
     *
     * @param int|null $acceptedDuplicityId
     *
     * @return $this
     */
    public function setAcceptedDuplicityId($acceptedDuplicityId = null)
    {
        $this->acceptedDuplicityId = $acceptedDuplicityId;

        return $this;
    }
}


