<?php
/**
 * SmartcardPurchase
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  Humansis\WebApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Humansis Web App
 *
 * This is an API documentation for Humansis Web App.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace Humansis\WebApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the SmartcardPurchase model.
 *
 * @package Humansis\WebApi\Model
 * @author  OpenAPI Generator team
 */
class SmartcardPurchase 
{
        /**
     * @var int|null
     * @SerializedName("id")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $id;

    /**
     * @var float|null
     * @SerializedName("value")
     * @Assert\Type("float")
     * @Type("float")
     */
    protected $value;

    /**
     * @var string|null
     * @SerializedName("currency")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $currency;

    /**
     * @var int|null
     * @SerializedName("beneficiaryId")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $beneficiaryId;

    /**
     * @var string|null
     * @SerializedName("dateOfPurchase")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $dateOfPurchase;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->id = isset($data['id']) ? $data['id'] : null;
        $this->value = isset($data['value']) ? $data['value'] : null;
        $this->currency = isset($data['currency']) ? $data['currency'] : null;
        $this->beneficiaryId = isset($data['beneficiaryId']) ? $data['beneficiaryId'] : null;
        $this->dateOfPurchase = isset($data['dateOfPurchase']) ? $data['dateOfPurchase'] : null;
    }

    /**
     * Gets id.
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param int|null $id
     *
     * @return $this
     */
    public function setId($id = null)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets value.
     *
     * @return float|null
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Sets value.
     *
     * @param float|null $value
     *
     * @return $this
     */
    public function setValue($value = null)
    {
        $this->value = $value;

        return $this;
    }

    /**
     * Gets currency.
     *
     * @return string|null
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Sets currency.
     *
     * @param string|null $currency
     *
     * @return $this
     */
    public function setCurrency($currency = null)
    {
        $this->currency = $currency;

        return $this;
    }

    /**
     * Gets beneficiaryId.
     *
     * @return int|null
     */
    public function getBeneficiaryId()
    {
        return $this->beneficiaryId;
    }

    /**
     * Sets beneficiaryId.
     *
     * @param int|null $beneficiaryId
     *
     * @return $this
     */
    public function setBeneficiaryId($beneficiaryId = null)
    {
        $this->beneficiaryId = $beneficiaryId;

        return $this;
    }

    /**
     * Gets dateOfPurchase.
     *
     * @return string|null
     */
    public function getDateOfPurchase()
    {
        return $this->dateOfPurchase;
    }

    /**
     * Sets dateOfPurchase.
     *
     * @param string|null $dateOfPurchase
     *
     * @return $this
     */
    public function setDateOfPurchase($dateOfPurchase = null)
    {
        $this->dateOfPurchase = $dateOfPurchase;

        return $this;
    }
}


