<?php
/**
 * SmartcardRedemptionCandidate
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  Humansis\WebApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Humansis Web App
 *
 * This is an API documentation for Humansis Web App.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace Humansis\WebApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the SmartcardRedemptionCandidate model.
 *
 * @package Humansis\WebApi\Model
 * @author  OpenAPI Generator team
 */
class SmartcardRedemptionCandidate 
{
        /**
     * @var int|null
     * @SerializedName("projectId")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $projectId;

    /**
     * @var int[]|null
     * @SerializedName("purchaseIds")
     * @Assert\All({
     *   @Assert\Type("int")
     * })
     * @Type("array<int>")
     */
    protected $purchaseIds;

    /**
     * @var float|null
     * @SerializedName("value")
     * @Assert\Type("float")
     * @Type("float")
     */
    protected $value;

    /**
     * @var string|null
     * @SerializedName("currency")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $currency;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->projectId = isset($data['projectId']) ? $data['projectId'] : null;
        $this->purchaseIds = isset($data['purchaseIds']) ? $data['purchaseIds'] : null;
        $this->value = isset($data['value']) ? $data['value'] : null;
        $this->currency = isset($data['currency']) ? $data['currency'] : null;
    }

    /**
     * Gets projectId.
     *
     * @return int|null
     */
    public function getProjectId()
    {
        return $this->projectId;
    }

    /**
     * Sets projectId.
     *
     * @param int|null $projectId
     *
     * @return $this
     */
    public function setProjectId($projectId = null)
    {
        $this->projectId = $projectId;

        return $this;
    }

    /**
     * Gets purchaseIds.
     *
     * @return int[]|null
     */
    public function getPurchaseIds(): ?array
    {
        return $this->purchaseIds;
    }

    /**
     * Sets purchaseIds.
     *
     * @param int[]|null $purchaseIds
     *
     * @return $this
     */
    public function setPurchaseIds(array $purchaseIds = null)
    {
        $this->purchaseIds = $purchaseIds;

        return $this;
    }

    /**
     * Gets value.
     *
     * @return float|null
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Sets value.
     *
     * @param float|null $value
     *
     * @return $this
     */
    public function setValue($value = null)
    {
        $this->value = $value;

        return $this;
    }

    /**
     * Gets currency.
     *
     * @return string|null
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Sets currency.
     *
     * @param string|null $currency
     *
     * @return $this
     */
    public function setCurrency($currency = null)
    {
        $this->currency = $currency;

        return $this;
    }
}


