<?php
/**
 * Transaction
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  Humansis\WebApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Humansis Web App
 *
 * This is an API documentation for Humansis Web App.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace Humansis\WebApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Transaction model.
 *
 * @package Humansis\WebApi\Model
 * @author  OpenAPI Generator team
 */
class Transaction 
{
        /**
     * @var int|null
     * @SerializedName("id")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $id;

    /**
     * @var string|null
     * @SerializedName("identifier")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $identifier;

    /**
     * ID of User
     *
     * @var int|null
     * @SerializedName("senderId")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $senderId;

    /**
     * @var string|null
     * @SerializedName("amountSent")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $amountSent;

    /**
     * @var string|null
     * @SerializedName("dateSent")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $dateSent;

    /**
     * @var string|null
     * @SerializedName("datePickuped")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $datePickuped;

    /**
     * one of /transactions/statuses
     *
     * @var string|null
     * @SerializedName("status")
     * @Assert\Choice({ "failure", "success", "no_phone" })
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $status;

    /**
     * @var string|null
     * @SerializedName("message")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $message;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->id = isset($data['id']) ? $data['id'] : null;
        $this->identifier = isset($data['identifier']) ? $data['identifier'] : null;
        $this->senderId = isset($data['senderId']) ? $data['senderId'] : null;
        $this->amountSent = isset($data['amountSent']) ? $data['amountSent'] : null;
        $this->dateSent = isset($data['dateSent']) ? $data['dateSent'] : null;
        $this->datePickuped = isset($data['datePickuped']) ? $data['datePickuped'] : null;
        $this->status = isset($data['status']) ? $data['status'] : null;
        $this->message = isset($data['message']) ? $data['message'] : null;
    }

    /**
     * Gets id.
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param int|null $id
     *
     * @return $this
     */
    public function setId($id = null)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets identifier.
     *
     * @return string|null
     */
    public function getIdentifier()
    {
        return $this->identifier;
    }

    /**
     * Sets identifier.
     *
     * @param string|null $identifier
     *
     * @return $this
     */
    public function setIdentifier($identifier = null)
    {
        $this->identifier = $identifier;

        return $this;
    }

    /**
     * Gets senderId.
     *
     * @return int|null
     */
    public function getSenderId()
    {
        return $this->senderId;
    }

    /**
     * Sets senderId.
     *
     * @param int|null $senderId  ID of User
     *
     * @return $this
     */
    public function setSenderId($senderId = null)
    {
        $this->senderId = $senderId;

        return $this;
    }

    /**
     * Gets amountSent.
     *
     * @return string|null
     */
    public function getAmountSent()
    {
        return $this->amountSent;
    }

    /**
     * Sets amountSent.
     *
     * @param string|null $amountSent
     *
     * @return $this
     */
    public function setAmountSent($amountSent = null)
    {
        $this->amountSent = $amountSent;

        return $this;
    }

    /**
     * Gets dateSent.
     *
     * @return string|null
     */
    public function getDateSent()
    {
        return $this->dateSent;
    }

    /**
     * Sets dateSent.
     *
     * @param string|null $dateSent
     *
     * @return $this
     */
    public function setDateSent($dateSent = null)
    {
        $this->dateSent = $dateSent;

        return $this;
    }

    /**
     * Gets datePickuped.
     *
     * @return string|null
     */
    public function getDatePickuped()
    {
        return $this->datePickuped;
    }

    /**
     * Sets datePickuped.
     *
     * @param string|null $datePickuped
     *
     * @return $this
     */
    public function setDatePickuped($datePickuped = null)
    {
        $this->datePickuped = $datePickuped;

        return $this;
    }

    /**
     * Gets status.
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Sets status.
     *
     * @param string|null $status  one of /transactions/statuses
     *
     * @return $this
     */
    public function setStatus($status = null)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Gets message.
     *
     * @return string|null
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Sets message.
     *
     * @param string|null $message
     *
     * @return $this
     */
    public function setMessage($message = null)
    {
        $this->message = $message;

        return $this;
    }
}


