<?php
/**
 * VendorSummaries
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  Humansis\WebApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Humansis Web App
 *
 * This is an API documentation for Humansis Web App.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace Humansis\WebApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the VendorSummaries model.
 *
 * @package Humansis\WebApi\Model
 * @author  OpenAPI Generator team
 */
class VendorSummaries 
{
        /**
     * @var int|null
     * @SerializedName("redeemedSmartcardPurchasesTotalCount")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $redeemedSmartcardPurchasesTotalCount;

    /**
     * @var float|null
     * @SerializedName("redeemedSmartcardPurchasesTotalValue")
     * @Assert\Type("float")
     * @Type("float")
     */
    protected $redeemedSmartcardPurchasesTotalValue;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->redeemedSmartcardPurchasesTotalCount = isset($data['redeemedSmartcardPurchasesTotalCount']) ? $data['redeemedSmartcardPurchasesTotalCount'] : null;
        $this->redeemedSmartcardPurchasesTotalValue = isset($data['redeemedSmartcardPurchasesTotalValue']) ? $data['redeemedSmartcardPurchasesTotalValue'] : null;
    }

    /**
     * Gets redeemedSmartcardPurchasesTotalCount.
     *
     * @return int|null
     */
    public function getRedeemedSmartcardPurchasesTotalCount()
    {
        return $this->redeemedSmartcardPurchasesTotalCount;
    }

    /**
     * Sets redeemedSmartcardPurchasesTotalCount.
     *
     * @param int|null $redeemedSmartcardPurchasesTotalCount
     *
     * @return $this
     */
    public function setRedeemedSmartcardPurchasesTotalCount($redeemedSmartcardPurchasesTotalCount = null)
    {
        $this->redeemedSmartcardPurchasesTotalCount = $redeemedSmartcardPurchasesTotalCount;

        return $this;
    }

    /**
     * Gets redeemedSmartcardPurchasesTotalValue.
     *
     * @return float|null
     */
    public function getRedeemedSmartcardPurchasesTotalValue()
    {
        return $this->redeemedSmartcardPurchasesTotalValue;
    }

    /**
     * Sets redeemedSmartcardPurchasesTotalValue.
     *
     * @param float|null $redeemedSmartcardPurchasesTotalValue
     *
     * @return $this
     */
    public function setRedeemedSmartcardPurchasesTotalValue($redeemedSmartcardPurchasesTotalValue = null)
    {
        $this->redeemedSmartcardPurchasesTotalValue = $redeemedSmartcardPurchasesTotalValue;

        return $this;
    }
}


