framework:
    test: ~
    session:
        storage_factory_id: session.storage.factory.mock_file
    profiler:
        collect: false
    messenger:
        transports:
            in_memory: 'in-memory://'
        routing:
            'Component\Smartcard\Messaging\Message\SmartcardPurchaseMessage': in_memory
            'Component\Import\Messaging\Message\ImportCheck': sync
            'Component\Import\Messaging\Message\ItemBatch': sync
            'Component\Import\Messaging\Message\UploadFileFinished': sync
sentry:
    #do not log during unit tests
    dsn: ''

monolog:
    channels: [ 'import', 'exception' ]
    handlers:
        import:
            type: stream
            path: '%kernel.logs_dir%/imports.log'
            level: debug
            channels: [import]

parameters:
    mailer_dsn: 'null://null'
    frontendUrl: 'http://localhost:8080'
