parameters:
  vulnerability_weightingFile:        '%kernel.project_dir%/src/NewApiBundle/Resources/config/vulnerability/weighting.csv'
  vulnerability_scoringFileTemplate:  '%kernel.project_dir%/src/NewApiBundle/Resources/config/vulnerability/scoring_<<COUNTRY>>.csv'