<?php
/**
 * ProjectTest
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  Humansis\UserAppLegacyApi\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Humansis Offline App
 *
 * This is an API documentation for Humansis Offine App.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace Humansis\UserAppLegacyApi\Model;

use PHPUnit\Framework\TestCase;

/**
 * ProjectTest Class Doc Comment
 *
 * @category    Class */
// * @description Project
/**
 * @package     Humansis\UserAppLegacyApi\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 */
class ProjectTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Project"
     */
    public function testProject()
    {
        $testProject = new Project();
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "numberOfHouseholds"
     */
    public function testPropertyNumberOfHouseholds()
    {
    }
}
