<?php

namespace BeneficiaryBundle\Repository;

use BeneficiaryBundle\Entity\Household;
use DistributionBundle\Repository\AbstractCriteriaRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\QueryBuilder;

/**
 * BeneficiaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeneficiaryRepository extends AbstractCriteriaRepository
{

    /**
     * Get the head of household
     *
     * @param Household $household
     * @return mixed
     */
    public function getHeadOfHousehold(Household $household)
    {
        $qb = $this->createQueryBuilder("b");
        $q = $qb->where("b.household = :household")
            ->andWhere("b.status = 1")
            ->setParameter("household", $household);

        try
        {
            return $q->getQuery()->getSingleResult();
        }
        catch (NoResultException $e)
        {
            return null;
        }
        catch (NonUniqueResultException $e)
        {
            return null;
        }
    }

    /**
     * Get the head of household
     *
     * @param $householdId
     * @return mixed
     */
    public function getHeadOfHouseholdId($householdId)
    {
        $qb = $this->createQueryBuilder("b");
        $q = $qb->leftJoin("b.household", "hh")
            ->andWhere("hh.id = :id")
            ->andWhere("b.status = 1")
            ->setParameter("id", $householdId);

        try
        {
            return $q->getQuery()->getSingleResult();
        }
        catch (NoResultException $e)
        {
            return null;
        }
        catch (NonUniqueResultException $e)
        {
            return null;
        }
    }

    /**
     * @param $onlyCount
     * @param $countryISO3
     * @param $groupGlobal
     * @return QueryBuilder
     */
    public function configurationQueryBuilder($onlyCount, $countryISO3, $groupGlobal)
    {
        $qb = $this->createQueryBuilder("b");

        if ($onlyCount)
            $qb->select("count(b)");

        $qb->leftJoin("b.household", "hh");
        $this->setCountry($qb, $countryISO3);

        if (null !== $groupGlobal)
        {
            $qb->andWhere("b.status = :status")
                ->setParameter("status", $groupGlobal);
        }

        return $qb;
    }

    /**
     * Create sub request. The main request while found household inside the subrequest (and others subrequest)
     * The household must have at least one beneficiary with the condition respected ($field $operator $value / Example: gender = 0)
     *
     * @param QueryBuilder $qb
     * @param $i
     * @param $countryISO3
     * @param array $filters
     */
    public function whereDefault(QueryBuilder &$qb, $i, $countryISO3, array $filters)
    {
        $qb->andWhere("b.{$filters["field_string"]} {$filters["condition_string"]} :val$i")
            ->setParameter("val$i", $filters["value_string"]);
    }

    /**
     * Create sub request. The main request while found household inside the subrequest (and others subrequest)
     * The household must respect the value of the country specific ($idCountrySpecific), depends on operator and value
     *
     * @param QueryBuilder $qb
     * @param $i
     * @param $countryISO3
     * @param array $filters
     */
    protected function whereVulnerabilityCriterion(QueryBuilder &$qb, $i, $countryISO3, array $filters)
    {
        $qb->leftJoin("b.vulnerabilityCriteria", "vc$i")
            ->andWhere("vc$i.id = :idvc$i")
            ->setParameter("idvc$i", $filters["id"]);
    }

    /**
     * Create sub request. The main request while found household inside the subrequest (and others subrequest)
     * The household must respect the value of the country specific ($idCountrySpecific), depends on operator and value
     *
     * @param QueryBuilder $qb
     * @param $i
     * @param $countryISO3
     * @param array $filters
     */
    protected function whereCountrySpecific(QueryBuilder &$qb, $i, $countryISO3, array $filters)
    {
        $qb->leftJoin("hh.countrySpecificAnswers", "csa$i")
            ->andWhere("csa$i.countrySpecific = :countrySpecific$i")
            ->setParameter("countrySpecific$i", $filters["id"])
            ->andWhere("csa$i.answer {$filters["condition_string"]} :value$i")
            ->setParameter("value$i", $filters["value_string"]);
    }

    /**
     * Set the country iso3 in the query on Household (with alias 'hh{id}'
     *
     * @param QueryBuilder $qb
     * @param $countryISO3
     * @param string $i
     */
    protected function setCountry(QueryBuilder &$qb, $countryISO3, $i = '')
    {
        $qb->leftJoin("hh$i.location", "l$i")
            ->andWhere("l$i.countryIso3 = :countryIso3")
            ->setParameter("countryIso3", $countryISO3);
    }
}
