<?php

namespace BeneficiaryBundle\Repository;

use NewApiBundle\Entity\Beneficiary;
use NewApiBundle\Entity\CountrySpecific;
use NewApiBundle\Entity\Household;
use CommonBundle\Repository\LocationRepository;
use DistributionBundle\Entity\Assistance;
use CommonBundle\Entity\Location;
use DistributionBundle\Enum\AssistanceTargetType;
use DistributionBundle\Repository\AbstractCriteriaRepository;
use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\Query\Expr\Andx;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use NewApiBundle\Component\Assistance\Domain\SelectionCriteria;
use NewApiBundle\Component\Assistance\DTO\CriteriaGroup;
use NewApiBundle\Component\Import\Identity\NationalIdHashSet;
use NewApiBundle\DBAL\PersonGenderEnum;
use NewApiBundle\Entity\Import;
use NewApiBundle\Enum\NationalIdType;
use NewApiBundle\Enum\ReliefPackageState;
use NewApiBundle\Enum\SelectionCriteriaField;
use NewApiBundle\Enum\VulnerabilityCriteria;
use NewApiBundle\InputType\BeneficiaryFilterInputType;
use NewApiBundle\InputType\BeneficiaryOrderInputType;
use NewApiBundle\Request\Pagination;
use ProjectBundle\DBAL\LivelihoodEnum;
use ProjectBundle\Entity\Project;
use Doctrine\ORM\Query\Expr\Join;
use VoucherBundle\Entity\Smartcard;
use VoucherBundle\Enum\SmartcardStates;

/**
 * BeneficiaryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeneficiaryRepository extends AbstractCriteriaRepository
{
    public const
        BNF_ASSISTANCE_CONTEXT_ARCHIVED = 'archived',
        BNF_ASSISTANCE_CONTEXT_REMOVED = 'removed';

    /**
     * @var LocationRepository
     */
    private $locationRepository;

    public function injectLocationRepository(LocationRepository $locationRepository)
    {
        $this->locationRepository = $locationRepository;
    }

    /**
     * Get all beneficiaries in a selected project.
     *
     * @param Project $project
     * @param string  $target
     *
     * @return mixed
     */
    public function getAllOfProject(Project $project, string $target)
    {
        $projectId = $project->getId();
        $qb = $this->createQueryBuilder('b');
        if (AssistanceTargetType::HOUSEHOLD === $target) {
            $q = $qb->leftJoin('b.household', 'hh')
                ->where(':project MEMBER OF hh.projects')
                ->andWhere('b.status = 1')
                ->andWhere('b.archived = 0')
                ->setParameter('project', $projectId);
        } elseif (AssistanceTargetType::INDIVIDUAL === $target) {
            $q = $qb->leftJoin('b.household', 'hh')
                ->andWhere(':project MEMBER OF hh.projects')
                ->andWhere('b.archived = 0')
                ->setParameter('project', $projectId);
        } else {
            return [];
        }

        return $q->getQuery()->getResult();
    }

    /**
     * @param Project    $project
     * @param string     $target
     * @param Assistance $excludedAssistance
     *
     * @return array|float|int|mixed|string
     */
    public function getNotSelectedBeneficiariesOfProject(Project $project, string $target, Assistance $excludedAssistance)
    {
        $excludedAssistanceDQL = "SELECT ben.id FROM DistributionBundle\Entity\AssistanceBeneficiary db LEFT JOIN db.beneficiary ab INNER JOIN NewApiBundle\Entity\Beneficiary ben WITH ben.id = ab.id WHERE db.assistance = :assistance";
        $projectId = $project->getId();

        $qb = $this->createQueryBuilder('b');
        if (AssistanceTargetType::HOUSEHOLD === $target) {
            $q = $qb->leftJoin('b.household', 'hh')
                ->where(':project MEMBER OF hh.projects')
                ->andWhere('b.status = 1')
                ->andWhere('b.archived = 0')
                ->andWhere($qb->expr()->notIn('b.id', $excludedAssistanceDQL))
                ->setParameter('project', $projectId)
                ->setParameter('assistance', $excludedAssistance);
        } elseif (AssistanceTargetType::INDIVIDUAL === $target) {
            $q = $qb->leftJoin('b.household', 'hh')
                ->andWhere(':project MEMBER OF hh.projects')
                ->andWhere('b.archived = 0')
                ->andWhere($qb->expr()->notIn('b.id', $excludedAssistanceDQL))
                ->setParameter('project', $projectId)
                ->setParameter('assistance', $excludedAssistance);
        } else {
            return [];
        }

        return $q->getQuery()->getResult();
    }

    public function findByUnarchived(array $byArray)
    {
        $qb = $this->createQueryBuilder('b');
        $q = $qb->leftJoin('b.household', 'hh')
            ->where('hh.archived = 0');
        foreach ($byArray as $key => $value) {
            $q = $q->andWhere('b.'.$key.' = :value'.$key)
                ->setParameter('value'.$key, $value);
        }

        return $q->getQuery()->getResult();
    }

    /**
     * @param Project $project
     *
     * @return QueryBuilder
     */
    public function getQbUnarchivedByProject(Project $project): QueryBuilder
    {
        $qb = $this->createQueryBuilder("bnf");

        return $qb->leftJoin("bnf.projects", "p")
            ->where("p = :project")
            ->setParameter("project", $project)
            ->andWhere("bnf.archived = 0");
    }

    /**
     * @param Project $project
     *
     * @return null|\DateTimeInterface
     * @throws NonUniqueResultException
     */
    public function getLastModifiedByProject(Project $project): ?\DateTimeInterface
    {
        $qb = $this->getQbUnarchivedByProject($project);
        $qb->select('bnf.updatedOn')
            ->orderBy('bnf.updatedOn', 'DESC')
            ->setFirstResult(0)
            ->setMaxResults(1);

        try {
            return $qb->getQuery()->getSingleResult(AbstractQuery::HYDRATE_ARRAY)['updatedOn'];
        } catch (NoResultException $e) {
            return null;
        }
    }

    public function getUnarchivedByProject(Project $project): iterable
    {
        $q = $this->getQbUnarchivedByProject($project);

        return $q->getQuery()->getResult();
    }

    public function findByName(string $givenName, ?string $parentsName, string $familyName, ?string $gender = null, Household $household = null)
    {
        $qbr = $this->createQueryBuilder('b')
            ->leftJoin('b.household', 'hh')
            ->join('b.person', 'p')
            ->andWhere('hh.archived = 0')
            ->andWhere('p.localGivenName = :givenName')
            ->andWhere('(p.localParentsName = :parentsName OR (p.localParentsName IS NULL AND :parentsName IS NULL) )')
            ->andWhere('p.localFamilyName = :familyName')
            ->setParameter('givenName', $givenName)
            ->setParameter('parentsName', $parentsName)
            ->setParameter('familyName', $familyName);

        if (null !== $gender) {
            $qbr
                ->andWhere('p.gender = :gender')
                ->setParameter('gender', PersonGenderEnum::valueToDB($gender));
        }

        if (!is_null($household)) {
            $qbr->andWhere('hh.id = :hhId')
                ->setParameter('hhId', $household->getId());
        }

        return $qbr->getQuery()
            ->getResult();
    }

    public function getAllInCountry(string $iso3)
    {
        $qb = $this->createQueryBuilder('b');
        $this->beneficiariesInCountry($qb, $iso3);
        $qb->andWhere('hh.archived = 0');

        return $qb->getQuery()->getResult();
    }

    public function countAllInCountry(string $iso3)
    {
        $qb = $this->createQueryBuilder('b');
        $this->beneficiariesInCountry($qb, $iso3);
        $qb->andWhere('hh.archived = 0')
            ->select('COUNT(DISTINCT b)');

        return $qb->getQuery()->getSingleScalarResult();
    }

    /**
     * Counts Household members in project.
     *
     * @param Project $project
     *
     * @return int
     *
     * @throws NoResultException
     * @throws NonUniqueResultException
     */
    public function countAllInProject(Project $project): int
    {
        $qb = $this->createQueryBuilder('b');
        $qb
            ->select('COUNT(DISTINCT b)')
            ->join('b.household', 'hh')
            ->where(':project MEMBER OF hh.projects')
            ->setParameter('project', $project)
            ->andWhere('b.archived = 0');

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function findIdentity(string $idType, string $idNumber, ?string $iso3 = null, ?Household $household = null)
    {
        $qb = $this->createQueryBuilder('b')
            ->join('b.person', 'p')
            ->join('b.household', 'hh')
            ->join('p.nationalIds', 'id')
            ->andWhere('b.archived = 0')
            ->andWhere('hh.archived = 0')
            ->andWhere('id.idType = :idType')
            ->andWhere('id.idNumber = :idNumber')
            ->setParameter('idNumber', $idNumber)
            ->setParameter('idType', $idType);

        if (null !== $iso3) {
            $qb->join('hh.projects', 'project')
                ->andWhere('project.iso3 = :country')
                ->setParameter('country', $iso3);
        }

        if (null !== $household) {
            $qb->andWhere('hh.id = :hhId')
                ->setParameter('hhId', $household->getId());
        }

        return $qb->getQuery()
            ->getResult();
    }

    public function findByIdentityAndAssistance($idNumber, Assistance $assistance, ?CountrySpecific $countrySpecific)
    {
        $qb = $this->createQueryBuilder('b')
            ->join('b.person', 'p')
            ->join('b.household', 'hh')
            ->join('b.assistanceBeneficiary', 'ab', Join::WITH, 'ab.removed=0')

            ->leftJoin('p.nationalIds', 'id')
            ->leftJoin('hh.countrySpecificAnswers', 'countrySpecificAnswer', Join::WITH,
                'IDENTITY(countrySpecificAnswer.countrySpecific) = :countrySpecificId')
            ->andWhere('ab.assistance = :assistance')
            ->andWhere('b.archived = 0')
            ->andWhere('hh.archived = 0')
            ->andWhere('id.idNumber = :idNumber OR countrySpecificAnswer.answer = :idNumber')
            ->setParameter('idNumber', $idNumber)
            ->setParameter('assistance', $assistance)
            ->setParameter('countrySpecificId', $countrySpecific ? $countrySpecific->getId() : null);

        return $qb->getQuery()
            ->getResult();
    }

    /**
     * @param string  $documentNumber
     * @param string  $documentType
     * @param Project $project
     *
     * @return float|int|mixed|string
     */
    public function findByIdentityAndProject(string $documentNumber,string $documentType, Project $project)
    {
        $qb = $this->createQueryBuilder('b')
            ->join('b.person', 'p')
            ->join('b.household', 'hh')

            ->leftJoin('p.nationalIds', 'id')
            ->where(':project MEMBER OF hh.projects')
            ->andWhere('b.archived = 0')
            ->andWhere('hh.archived = 0')
            ->andWhere('id.idNumber = :idNumber')
            ->andWhere('id.idType = :idType')

            ->setParameter('idNumber', $documentNumber)
            ->setParameter('idType', $documentType)
            ->setParameter('project', $project);
        return $qb->getQuery()
            ->getResult();
    }

    /**
     * @param array  $documentNumbers
     * @param string $idType
     *
     * @return float|int|mixed|string
     */
    public function findByIdentities(array $documentNumbers,string $idType)
    {
        $qb = $this->createQueryBuilder('b')
            ->join('b.person', 'p')
            ->join('b.household', 'hh')

            ->leftJoin('p.nationalIds', 'id')
            ->andWhere('id.idNumber IN (:idNumbers)')
            ->andWhere('id.idType = :idType')
            ->andWhere('b.archived = 0')
            ->andWhere('hh.archived = 0')
            ->setParameter('idNumbers', $documentNumbers)
            ->setParameter('idType', $idType);
        return $qb->getQuery()
            ->getResult();
    }

    public function findIdentitiesByNationalIds(string $iso3, NationalIdHashSet $ids)
    {
        $qb = $this->createQueryBuilder('b')
            ->join('b.person', 'p')
            ->join('b.household', 'hh')
            ->join('p.nationalIds', 'id')
            ->andWhere('b.archived = 0')
            ->andWhere('hh.archived = 0')
            ->andWhere('id.idNumber IN (:idNumbers)')
            ->andWhere('id.idType IN (:idTypes)')
            ->setParameter('idNumbers', $ids->getNumbers())
            ->setParameter('idTypes', $ids->getTypes());

        if (null !== $iso3) {
            $qb->join('hh.projects', 'project')
                ->andWhere('project.iso3 = :country')
                ->setParameter('country', $iso3);
        }

        return $qb->getQuery()
            ->getResult();
    }

    public function getAllofDistribution(Assistance $assistance)
    {
        $qb = $this->createQueryBuilder('b');
        $q = $qb->leftJoin('b.assistanceBeneficiary', 'db')
            ->where('db.assistance = :assistance')
            ->setParameter('assistance', $assistance);

        return $q->getQuery()->getResult();
    }

    public function getImported(Import $import)
    {
        $qb = $this->createQueryBuilder('b');
        $q = $qb->innerJoin('b.importBeneficiaries', 'ib')
            ->where('ib.import = :import')
            ->setParameter('import', $import);

        return $q->getQuery()->getResult();
    }

    public function getNotRemovedofDistribution(Assistance $assistance)
    {
        $qb = $this->createQueryBuilder('b');
        $q = $qb->leftJoin('b.assistanceBeneficiary', 'db')
            ->where('db.assistance = :assistance')
            ->andWhere('db.removed = 0')
            ->setParameter('assistance', $assistance);

        return $q->getQuery()->getResult();
    }

    /**
     * Get the head of household.
     *
     * @param Household $household
     *
     * @return mixed
     */
    public function getHeadOfHousehold(Household $household)
    {
        $qb = $this->createQueryBuilder('b');
        $q = $qb->where('b.household = :household')
            ->andWhere('b.status = 1')
            ->setParameter('household', $household);

        try {
            return $q->getQuery()->getSingleResult();
        } catch (NoResultException $e) {
            return null;
        } catch (NonUniqueResultException $e) {
            return null;
        }
    }

    /**
     * Get the head of household.
     *
     * @param $householdId
     *
     * @return mixed
     */
    public function getHeadOfHouseholdId($householdId)
    {
        $qb = $this->createQueryBuilder('b');
        $q = $qb->leftJoin('b.household', 'hh')
            ->andWhere('hh.id = :id')
            ->andWhere('b.status = 1')
            ->setParameter('id', $householdId);

        try {
            return $q->getQuery()->getSingleResult();
        } catch (NoResultException $e) {
            return null;
        } catch (NonUniqueResultException $e) {
            return null;
        }
    }

    public function countByResidencyStatus(Assistance $assistance, string $residencyStatus): int
    {
        if (AssistanceTargetType::HOUSEHOLD === $assistance->getTargetType()) {
            $qb = $this->createQueryBuilder('hhm')
                ->select('COUNT(hhm)')
                ->join('hhm.household', 'h')
                ->join('h.beneficiaries', 'hhh')
                ->join('hhh.assistanceBeneficiary', 'db', 'WITH', 'db.removed=0')
                ->andWhere('db.assistance = :assistance')
                ->andWhere('hhm.residencyStatus = :residencyStatus')
                ->andWhere('hhm.archived = 0')
                ->setParameter('assistance', $assistance)
                ->setParameter('residencyStatus', $residencyStatus);
        } else {
            $qb = $this->createQueryBuilder('b')
                ->select('COUNT(DISTINCT b)')
                ->join('b.assistanceBeneficiary', 'db', 'WITH', 'db.removed=0')
                ->andWhere('db.assistance = :assistance')
                ->andWhere('b.residencyStatus = :residencyStatus')
                ->andWhere('b.archived = 0')
                ->setParameter('assistance', $assistance)
                ->setParameter('residencyStatus', $residencyStatus);
        }

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function countHouseholdHeadsByGender(Assistance $assistance, string $gender): int
    {
        $qb = $this->createQueryBuilder('b');
        $qb->select('COUNT(DISTINCT b)');
        $this->whereInDistribution($qb, $assistance);
        $this->whereHouseHoldHead($qb);
        $this->whereGender($qb, $gender);
        $qb->andWhere('b.archived = 0');

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function countByAgeAndByGender(Assistance $distribution, int $gender, int $minAge, int $maxAge, \DateTimeInterface $distributionDate): int
    {
        $maxDateOfBirth = clone $distributionDate;
        $minDateOfBirth = clone $distributionDate;
        $maxDateOfBirth->sub(new \DateInterval('P'.$minAge.'Y'));
        $minDateOfBirth->sub(new \DateInterval('P'.$maxAge.'Y'));

        if (AssistanceTargetType::HOUSEHOLD === $distribution->getTargetType()) {
            $qb = $this->createQueryBuilder('hhm')
                ->select('COUNT(hhm)')
                ->join('hhm.person', 'p', 'WITH', 'p.gender = :g AND p.dateOfBirth >= :minDateOfBirth AND p.dateOfBirth < :maxDateOfBirth')
                ->join('hhm.household', 'h')
                ->join('h.beneficiaries', 'hhh')
                ->join('hhh.assistanceBeneficiary', 'db', 'WITH', 'db.removed=0')
                ->andWhere('db.assistance = :assistance')
                ->andWhere('hhm.archived = 0')
                ->setParameter('assistance', $distribution)
                ->setParameter('g', $gender)
                ->setParameter('minDateOfBirth', $minDateOfBirth)
                ->setParameter('maxDateOfBirth', $maxDateOfBirth);
        } else {
            $qb = $this->createQueryBuilder('b')
                ->select('COUNT(b)')
                ->join('b.person', 'p', 'WITH', 'p.gender = :g AND p.dateOfBirth >= :minDateOfBirth AND p.dateOfBirth < :maxDateOfBirth')
                ->join('b.distributionBeneficiaries', 'db', 'WITH', 'db.removed=0')
                ->andWhere('db.assistance = :assistance')
                ->andWhere('b.archived = 0')
                ->setParameter('assistance', $distribution)
                ->setParameter('g', $gender)
                ->setParameter('minDateOfBirth', $minDateOfBirth)
                ->setParameter('maxDateOfBirth', $maxDateOfBirth);
        }

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function countServed(Assistance $distribution, string $modalityType): int
    {
        $qb = $this->createQueryBuilder('b');
        $qb->select('COUNT(DISTINCT b)');
        $this->whereInDistribution($qb, $distribution);

        if ('Mobile Money' === $modalityType) {
            $qb->innerJoin('db.transactions', 't', Join::WITH, 't.transactionStatus = 1');
        } else {
            if ($modalityType === 'QR Code Voucher') {
                $qb->innerJoin('db.booklets', 'bo', Join::WITH, 'bo.status = 1 OR bo.status = 2');
            } else {
                $qb->innerJoin('db.reliefPackages', 'rp', Join::WITH, 'rp.state = :distributed')
                    ->setParameter('distributed', ReliefPackageState::DISTRIBUTED);
            }
        }

        return $qb->getQuery()->getSingleScalarResult();
    }

    /**
     * @param         $onlyCount
     * @param         $countryISO3
     * @param Project $project
     *
     * @return QueryBuilder|void
     */
    public function configurationQueryBuilder($onlyCount, $countryISO3, Project $project = null)
    {
        $qb = $this->createQueryBuilder('b');

        if ($onlyCount) {
            $qb->select('count(b)');
        }
        if (null !== $project) {
            $qb->where(':idProject MEMBER OF hh.projects')
                ->setParameter('idProject', $project->getId());
        }
        $qb->leftJoin('b.household', 'hh');
        $this->setCountry($qb, $countryISO3);

        return $qb;
    }

    protected function whereInDistribution(QueryBuilder $qb, Assistance $assistance)
    {
        if (!in_array('db', $qb->getAllAliases())) {
            $qb->leftJoin(
                'b.distributionBeneficiaries',
                'db',
                Join::WITH,
                'db.removed = 0'
            );
            $qb->andWhere('db.assistance = :distribution');
            $qb->setParameter('distribution', $assistance);
        }
    }

    protected function whereHouseHoldHead(QueryBuilder $qb)
    {
        $qb->andWhere('b.status = :status');
        $qb->setParameter('status', 1); // status = HHH
    }

    protected function whereGender(QueryBuilder $qb, string $gender)
    {
        if (!in_array('p', $qb->getAllAliases())) {
            $qb->join('b.person', 'p');
        }
        $qb->andWhere('p.gender = :g');
        $qb->setParameter('g', PersonGenderEnum::valueToDB($gender));
    }

    protected function whereBornBetween(QueryBuilder &$qb, \DateTimeInterface $minDateOfBirth, \DateTimeInterface $maxDateOfBirth)
    {
        if (!in_array('p', $qb->getAllAliases())) {
            $qb->join('b.person', 'p');
        }
        $qb->andWhere('p.dateOfBirth >= :minDateOfBirth');
        $qb->andWhere('p.dateOfBirth < :maxDateOfBirth');
        $qb->setParameter('minDateOfBirth', $minDateOfBirth);
        $qb->setParameter('maxDateOfBirth', $maxDateOfBirth);
    }

    /**
     * Create sub request. The main request while found household inside the subrequest (and others subrequest)
     * The household must have at least one beneficiary with the condition respected ($field $operator $value / Example: gender = 0).
     *
     * @param QueryBuilder $qb
     * @param              $i
     * @param              $countryISO3
     * @param array        $filters
     */
    public function whereDefault(QueryBuilder &$qb, $i, $countryISO3, array $filters)
    {
        $qb->andWhere("b.{$filters['field_string']} {$filters['condition_string']} :val$i")
            ->setParameter("val$i", $filters['value_string']);
    }

    /**
     * Create sub request. The main request while found household inside the subrequest (and others subrequest)
     * The household must respect the value of the country specific ($idCountrySpecific), depends on operator and value.
     *
     * @param QueryBuilder $qb
     * @param              $i
     * @param              $countryISO3
     * @param array        $filters
     */
    protected function whereVulnerabilityCriterion(QueryBuilder &$qb, $i, $countryISO3, array $filters)
    {
        $qb->leftJoin('b.vulnerabilityCriteria', "vc$i")
            ->andWhere("vc$i.id = :idvc$i")
            ->setParameter("idvc$i", $filters['id_field']);
    }

    /**
     * Create sub request. The main request while found household inside the subrequest (and others subrequest)
     * The household must respect the value of the country specific ($idCountrySpecific), depends on operator and value.
     *
     * @param QueryBuilder $qb
     * @param              $i
     * @param              $countryISO3
     * @param array        $filters
     */
    protected function whereCountrySpecific(QueryBuilder &$qb, $i, $countryISO3, array $filters)
    {
        $qb->leftJoin('hh.countrySpecificAnswers', "csa$i")
            ->andWhere("csa$i.countrySpecific = :countrySpecific$i")
            ->setParameter("countrySpecific$i", $filters['id_field'])
            ->andWhere("csa$i.answer {$filters['condition_string']} :value$i")
            ->setParameter("value$i", $filters['value_string']);
    }

    public function countServedInCountry($iso3)
    {
        $qb = $this->createQueryBuilder('b');
        $this->beneficiariesInCountry($qb, $iso3);

        $qb->select('COUNT(DISTINCT b)')
            ->leftJoin('b.assistanceBeneficiary', 'db')
            ->leftJoin('db.booklets', 'bk')
            ->leftJoin('db.transactions', 't')
            ->leftJoin('db.reliefPackages', 'rp')
            ->andWhere('t.transactionStatus = 1 OR rp.state = :distributed OR bk.id IS NOT NULL')
            ->setParameter('distributed', ReliefPackageState::DISTRIBUTED);

        return $qb->getQuery()->getSingleScalarResult();
    }

    private function beneficiariesInCountry(QueryBuilder &$qb, $countryISO3)
    {
        $qb->leftJoin('b.household', 'hh');

        $householdRepository = $this->getEntityManager()->getRepository(Household::class);
        $householdRepository->whereHouseholdInCountry($qb, $countryISO3);
    }

    public function getDistributionBeneficiaries(CriteriaGroup $criteriaGroup, Project $project)
    {
        $hhRepository = $this->getEntityManager()->getRepository(Household::class);
        $qb = $hhRepository->getUnarchivedByProject($project);

        // First we get all the beneficiaries, and we store the headId for later
        $qb->leftJoin('hh.beneficiaries', 'b')
            ->select('DISTINCT b.id AS id')
            ->leftJoin('hh.beneficiaries', 'head')
            ->andWhere('head.status = 1')
            ->addSelect('head.id AS headId');

        // If a beneficiary has a criterion, they are selectable, therefore every criterion has to go in a orX()
        $userConditionsStatement = $qb->expr()->andX();
        /**
         * @var                   $index
         * @var SelectionCriteria $criterion
         */
        foreach ($criteriaGroup->getCriteria() as $index => $criterion) {
            $condition = ($criterion->getConditionOperator() === '!=') ? '<>' : $criterion->getConditionOperator();

            $forHousehold = $criterion->supportsHousehold();
            $forHead = $criterion->supportsHouseholdHead();
            $forIndividual = $criterion->supportsIndividual();

            $isVulnerability = $criterion->hasVulnerabilityCriteriaType();
            $isCSO = $criterion->hasCountrySpecificType();
            $isField = $criterion->hasTableFieldType();
            $isOther = $criterion->hasTypeOther();

            if ($forHousehold && $isCSO) {
                $this->getHouseholdWithCountrySpecificCriterion($qb, $criterion->getField(), $condition, $criterion, $index,
                    $userConditionsStatement);
            } elseif ($forHousehold && $isField) {
                $this->getHouseholdWithTableFieldCriterion($qb, $criterion->getField(), $condition, $criterion, $index, $userConditionsStatement);
            } elseif ($forHousehold && $isOther) {
                $this->getHouseholdWithOtherCriterion($qb, $criterion->getField(), $condition, $criterion, $index, $userConditionsStatement);
            } elseif ($forIndividual && $isVulnerability) {
                $this->addVulnerabilityCriterion($qb, 'b', (bool) $criterion->getValueString(), $criterion->getField(), $userConditionsStatement,
                    $index);
            } elseif ($forIndividual && $isField) {
                $this->getBeneficiaryWithTableFieldCriterion($qb, $criterion->getField(), $condition, $criterion, $index, $userConditionsStatement);
            } elseif ($forIndividual && $isOther) {
                $this->getBeneficiaryWithOtherCriterion($qb, $criterion->getField(), $condition, $criterion, $index, $userConditionsStatement);
            } elseif ($forHead && $isVulnerability) {
                $this->addVulnerabilityCriterion($qb, 'b', $condition, $criterion->getField(), $userConditionsStatement, $index);
            } elseif ($forHead && $isField) {
                $this->getHeadWithFieldCriterion($qb, $criterion->getField(), $condition, $criterion, $index, $userConditionsStatement);
            } elseif ($forHead && $isOther) {
                $this->getHeadWithOtherCriterion($qb, $criterion->getField(), $condition, $criterion, $index, $userConditionsStatement);
            }
            if ($criterion->hasCountrySpecificType()) {
                $qb->setParameter('parameter'.$index, $criterion->getValueString());
            }
        }
        $qb->andWhere($userConditionsStatement);

        return $qb->getQuery()->getResult();
    }

    private function getHouseholdWithCountrySpecificCriterion(
        QueryBuilder      &$qb,
                          $field,
                          $condition,
        SelectionCriteria $criterion,
        int               $i,
        Andx              &$userConditionsStatement
    ) {
        // The selection criteria is a country Specific
        if (!$criterion->hasCountrySpecificType()) {
            throw new \InvalidArgumentException('Selection criterium isnt for CSO');
        }
        $qb->leftJoin('hh.countrySpecificAnswers', "csa$i", Join::WITH, "csa$i.answer $condition :parameter$i")
            ->leftJoin("csa$i.countrySpecific", "cs$i", Join::WITH, "cs$i.fieldString = :csName$i")
            ->setParameter("csName$i", $field);

        // To validate the criterion, the household has to answer the countrySpecific AND have the good value for it
        $andStatement = $qb->expr()->andX();
        $andStatement->add("cs$i.fieldString = :csName$i");
        $andStatement->add("csa$i.answer $condition :parameter$i");
        $userConditionsStatement->add($andStatement);
        $qb->addSelect("cs$i.fieldString");
    }

    private function getHouseholdWithTableFieldCriterion(
        QueryBuilder      &$qb,
                          $field,
                          $condition,
        SelectionCriteria $criterion,
        int               $i,
        Andx              &$userConditionsStatement
    ) {
        // The selection criteria is directly a field in the Household table
        if (!$criterion->hasTableFieldType()) {
            throw new \InvalidArgumentException('Selection criterium isnt for Table field criterium');
        }
        $userConditionsStatement->add("hh.$field$condition :parameter$i");
        $qb->addSelect("(CASE WHEN hh.$field$condition :parameter$i THEN hh.$field ELSE :null END) AS $field$i")
            ->setParameter('null', null);

        if ($criterion->getField() === SelectionCriteriaField::LIVELIHOD) {
            $qb->setParameter("parameter$i", LivelihoodEnum::valueToDB($criterion->getValueString()));
        } else {
            $qb->setParameter("parameter$i", $criterion->getValueString());
        }
    }

    private function getHouseholdWithOtherCriterion(
        QueryBuilder      &$qb,
                          $field,
                          $condition,
        SelectionCriteria $criterion,
        int               $i,
        Andx              &$userConditionsStatement
    ) {
        if (!$criterion->hasTypeOther()) {
            throw new \InvalidArgumentException('Selection criterium isnt for other criterium');
        }
        switch ($field) {
            case SelectionCriteriaField::HOUSEHOLD_SIZE:
                $userConditionsStatement->add("SIZE(hh.beneficiaries) $condition :parameter$i");
                $qb->addSelect("(CASE WHEN SIZE(hh.beneficiaries) $condition :parameter$i THEN SIZE(hh.beneficiaries) ELSE :null END) AS $field$i")
                    ->setParameter('null', null)
                    ->setParameter("parameter$i", $criterion->getValueString());
                break;
            case SelectionCriteriaField::LOCATION_TYPE:
                $qb->leftJoin("hh.householdLocations", "hl$i", Join::WITH, "hl$i.type $condition :parameter$i");
                $userConditionsStatement->add("hl$i.type $condition :parameter$i");
                $qb
                    ->addSelect("hl$i.type AS $field$i")
                    ->setParameter("parameter$i", $criterion->getValueString());
                break;
            case SelectionCriteriaField::CAMP_NAME:
                $qb->leftJoin("hh.householdLocations", "hl$i", Join::WITH, "hl$i.type = :camp")
                    ->leftJoin("hl$i.campAddress", "ca$i")
                    ->leftJoin("ca$i.camp", "c$i", Join::WITH, "c$i.id = :parameter$i")
                    ->setParameter('camp', 'camp');
                $userConditionsStatement->add("c$i.id = :parameter$i");
                $qb->addSelect("c$i.id AS $field$i");
                break;
            case SelectionCriteriaField::CURRENT_LOCATION:
                /** @var Location $location */
                $location = $this->locationRepository->find($criterion->getValueString());
                $locationsQb = $this->locationRepository->getChildrenLocationsQueryBuilder($location);

                $qb->leftJoin("hh.householdLocations", "hl$i")
                    ->leftJoin("hl$i.campAddress", "ca$i")
                    ->leftJoin("ca$i.camp", "c$i")
                    ->leftJoin("hl$i.address", "ad$i")
                    ->leftJoin(Location::class, "l$i", Join::WITH, "l$i.id = COALESCE(IDENTITY(c$i.location, 'id'), IDENTITY(ad$i.location, 'id'))")
                    ->andWhere("l$i.id IN ({$locationsQb->getDQL()})")
                    ->setParameter('currentRgt', $location->getRgt())
                    ->setParameter('currentLft', $location->getLft())
                    ->setParameter('currentLvl', $location->getLvl());
                break;
        }
    }

    private function getBeneficiaryWithTableFieldCriterion(
        QueryBuilder      &$qb,
                          $field,
                          $condition,
        SelectionCriteria $criterion,
        int               $i,
                          &$userConditionsStatement
    ) {
        if (!$criterion->hasTableFieldType()) {
            throw new \InvalidArgumentException('Selection criterium isnt for table field criterium');
        }
        if (in_array($field, ['dateOfBirth', 'gender'])) {
            if (!in_array('prsn', $qb->getAllAliases())) {
                $qb->join('b.person', 'prsn');
            }

            $userConditionsStatement->add("prsn.$field $condition :parameter$i");
            $qb->addSelect("(CASE WHEN prsn.$field$condition :parameter$i THEN prsn.$field ELSE :null END) AS $field$i")
                ->setParameter('null', null);
        } else {
            $userConditionsStatement->add("b.$field $condition :parameter$i");
            $qb->addSelect("(CASE WHEN b.$field $condition :parameter$i THEN b.$field ELSE :null END) AS $field$i")
                ->setParameter('null', null);
        }

        $qb->setParameter("parameter$i", $criterion->getValueString());
    }

    private function getBeneficiaryWithOtherCriterion(
        QueryBuilder      &$qb,
                          $field,
                          $condition,
        SelectionCriteria $criterion,
        int               $i,
                          &$userConditionsStatement
    ) {
        if (!$criterion->hasTypeOther()) {
            throw new \InvalidArgumentException('Selection criterium isnt for other criterium');
        }
        switch ($field) {
            case SelectionCriteriaField::HAS_NOT_BEEN_IN_DISTRIBUTIONS_SINCE:
                $qb->leftJoin('b.assistanceBeneficiary', "db$i")
                    ->leftJoin("db$i.assistance", "d$i")
                    // If has criteria, add it to the select to calculate weight later
                    ->addSelect("(CASE WHEN d$i.dateDistribution < :parameter$i THEN d$i.dateDistribution WHEN SIZE(b.assistanceBeneficiary) = 0 THEN :noDistribution ELSE :null END) AS {$criterion->getField()}$i")
                    ->having($criterion->getField().$i." IS NOT NULL")
                    ->setParameter('noDistribution', 'noDistribution')
                    ->setParameter('null', null)
                    ->setParameter("parameter$i", $criterion->getValueString());
                break;
        }

    }

    private function addVulnerabilityCriterion(
        QueryBuilder &$qb,
                     $on,
        bool         $hasVulnerability,
                     $vulnerabilityName,
        Andx         &$userConditionsStatement,
        int          $i
    ) {
        // Find a way to act directly on the join table beneficiary_vulnerability
        if ($hasVulnerability) {
            $qb->leftJoin("$on.vulnerabilityCriteria", "vc$i", Join::WITH, "vc$i.fieldString = :vulnerability$i");
            $userConditionsStatement->add($qb->expr()->eq("vc$i.fieldString", ":vulnerability$i"));
            // If has criteria, add it to the select to calculate weight later
            $qb->addSelect("vc$i.fieldString AS $on$vulnerabilityName$i");
        } else {

            // The beneficiary doesn"t have a vulnerability A if all their vulnerabilities are != A or if they have no vulnerabilities
            $qb->leftJoin("$on.vulnerabilityCriteria", "vc$i", Join::WITH, "vc$i.fieldString <> :vulnerability$i");

            $subQuery = $this->_em->createQueryBuilder();
            $subQuery
                ->select("b2$i.id")
                ->from(Beneficiary::class, "b2$i")
                ->leftJoin("b2$i.vulnerabilityCriteria", "vc2$i")
                ->andWhere("vc2$i.fieldString = :vulnerability$i")
                ->andWhere("b2$i.id = $on.id");
            $userConditionsStatement->add("$on.id NOT IN ({$subQuery->getDQL()})");

            // If has criteria, add it to the select to calculate weight later
            $qb->addSelect("(CASE WHEN vc$i.fieldString <> :vulnerability$i THEN vc$i.fieldString WHEN SIZE($on.vulnerabilityCriteria) = 0 THEN :noCriteria ELSE :null END) AS $on$vulnerabilityName$i")
                ->setParameter('noCriteria', 'noCriteria')
                ->setParameter('null', null);
        }
        $qb->setParameter('vulnerability'.$i, $vulnerabilityName);
    }

    private function hasValidSmartcardCriterion(QueryBuilder &$qb, string $on, bool $value, int $i)
    {
        $subQueryForSC = $this->_em->createQueryBuilder()
            ->select("sc$i.id")
            ->from(Smartcard::class, "sc$i")
            ->andWhere("IDENTITY(sc$i.beneficiary) = $on.id")
            ->andWhere("sc$i.state IN ('".SmartcardStates::ACTIVE."')")
            ->getDQL();

        if ($value) {
            $qb->andWhere("EXISTS($subQueryForSC)");
        } else {
            $qb->andWhere("NOT EXISTS($subQueryForSC)");
        }
    }

    private function getHeadWithFieldCriterion(
        QueryBuilder      &$qb,
                          $field,
                          $condition,
        SelectionCriteria $criterion,
        int               $i,
        Andx              &$userConditionsStatement
    ) {
        // The selection criteria is directly a field in the Beneficiary table
        if (!$criterion->hasTableFieldType()) {
            throw new \InvalidArgumentException('Selection criterium isnt table field criterium');
        }

        $qb->leftJoin('hh.beneficiaries', "hhh$i")
            ->andWhere("hhh$i.status = 1");
        $qb->join("hhh$i.person", "prsn$i");

        // The criterion name identifies the criterion (eg. headOfHouseholdDateOfBirth) whereas the field is gonna identify the table field (eg. dateOfBirth) in the Beneficiary table
        $criterionName = $field;
        switch ($field) {
            case SelectionCriteriaField::HEAD_OF_HOUSEHOLD_DATE_OF_BIRTH:
                $userConditionsStatement->add("prsn$i.dateOfBirth $condition :parameter$i");
                $qb->addSelect("(CASE WHEN prsn$i.dateOfBirth $condition :parameter$i THEN prsn$i.dateOfBirth ELSE :null END) AS $criterionName$i")
                    ->setParameter('null', null)
                    ->setParameter("parameter$i", $criterion->getValueString());
                break;
            case SelectionCriteriaField::GENDER:
                $userConditionsStatement->add("prsn$i.gender $condition :parameter$i");
                $qb->addSelect("(CASE WHEN prsn$i.gender $condition :parameter$i THEN prsn$i.gender ELSE :null END) AS $criterionName$i")
                    ->setParameter('null', null)
                    ->setParameter("parameter$i", $criterion->getValueString());
                break;
            default:
                $userConditionsStatement->add("hhh$i.$field.$condition :parameter$i");
                $qb->addSelect("(CASE WHEN hhh$i.$field $condition :parameter$i THEN hhh$i.$field ELSE :null END) AS $criterionName$i")
                    ->setParameter('null', null)
                    ->setParameter("parameter$i", $criterion->getValueString());
        }
    }

    private function getHeadWithOtherCriterion(&$qb, $field, $condition, SelectionCriteria $criterion, int $i, &$userConditionsStatement)
    {
        if (!$criterion->hasTypeOther()) {
            throw new \InvalidArgumentException('Selection criterium isnt for other criterium');
        }

        $qb->leftJoin('hh.beneficiaries', "hhh$i")
            ->andWhere("hhh$i.status = 1");
        $qb->join("hhh$i.person", "prsn$i");

        switch ($field) {
            case SelectionCriteriaField::DISABLED_HEAD_OF_HOUSEHOLD:
                $this->addVulnerabilityCriterion($qb, 'hhh'.$i, (bool) $criterion->getValueString(), VulnerabilityCriteria::DISABLED,
                    $userConditionsStatement, $i);
                break;
            case SelectionCriteriaField::HAS_VALID_SMARTCARD:
                $this->hasValidSmartcardCriterion($qb, 'hhh'.$i, (bool) $criterion->getValueString(), $i);
                break;
        }
    }

    /**
     * @param Household $household
     *
     * @return int
     *
     * @throws NoResultException
     * @throws NonUniqueResultException
     */
    public function countByHousehold(Household $household): int
    {
        return $this->createQueryBuilder('b')
            ->select('COUNT(DISTINCT b)')
            ->where('b.household = :household')
            ->andWhere('b.archived = 0')
            ->setParameter('household', $household)
            ->getQuery()->getSingleScalarResult();
    }

    /**
     * @param BeneficiaryFilterInputType $filterInputType
     *
     * @return Paginator
     */
    public function findByParams(BeneficiaryFilterInputType $filterInputType): Paginator
    {
        $qbr = $this->createQueryBuilder('b')
            ->andWhere('b.archived = 0');

        if ($filterInputType->hasIds()) {
            $qbr->andWhere('b.id IN (:ids)')
                ->setParameter('ids', $filterInputType->getIds());
        }

        return new Paginator($qbr);
    }

    /**
     * @param Assistance                      $assistance
     * @param BeneficiaryFilterInputType|null $filter
     * @param BeneficiaryOrderInputType|null  $orderBy
     * @param Pagination|null                 $pagination
     * @param array|null                      $context
     *
     * @return Paginator|Assistance[]
     */
    public function findByAssistance(
        Assistance                  $assistance,
        ?BeneficiaryFilterInputType $filter,
        ?BeneficiaryOrderInputType  $orderBy = null,
        ?Pagination                 $pagination = null,
        ?array                      $context = null
    ): Paginator {
        $qbr = $this->createQueryBuilder('b')
            ->join('b.assistanceBeneficiary', 'ab')
            ->leftJoin('b.person', 'p')
            ->andWhere('ab.assistance = :assistance')
            ->setParameter('assistance', $assistance);

        if ($context) {
            if (array_key_exists(self::BNF_ASSISTANCE_CONTEXT_ARCHIVED, $context)) {
                $qbr->andWhere('b.archived = :archived')
                    ->setParameter('archived', $context[self::BNF_ASSISTANCE_CONTEXT_ARCHIVED]);
            }
            if (array_key_exists(self::BNF_ASSISTANCE_CONTEXT_REMOVED, $context)) {
                $qbr->andWhere('ab.removed = :removed')
                    ->setParameter('removed', self::BNF_ASSISTANCE_CONTEXT_REMOVED);
            }
        }

        if ($pagination) {
            $qbr->setMaxResults($pagination->getLimit());
            $qbr->setFirstResult($pagination->getOffset());
        }

        if ($filter) {
            if ($filter->hasFulltext()) {
                $qbr->andWhere('(p.localGivenName LIKE :fulltext OR 
                                p.localFamilyName LIKE :fulltext OR
                                p.localParentsName LIKE :fulltext OR
                                p.enGivenName LIKE :fulltext OR
                                p.enFamilyName LIKE :fulltext OR
                                p.enParentsName LIKE :fulltext OR
                                p.enParentsName LIKE :fulltext)')
                    ->setParameter('fulltext', '%'.$filter->getFulltext().'%');
            }
        }

        if ($orderBy) {
            foreach ($orderBy->toArray() as $name => $direction) {
                switch ($name) {
                    case BeneficiaryOrderInputType::SORT_BY_ID:
                        $qbr->orderBy('b.id', $direction);
                        break;
                    case BeneficiaryOrderInputType::SORT_BY_LOCAL_FAMILY_NAME:
                        $qbr->orderBy('p.localFamilyName', $direction);
                        break;
                    case BeneficiaryOrderInputType::SORT_BY_LOCAL_GIVEN_NAME:
                        $qbr->orderBy('p.localGivenName', $direction);
                        break;
                    case BeneficiaryOrderInputType::SORT_BY_NATIONAL_ID:
                        $qbr->leftJoin('p.nationalIds', 'n', 'WITH', 'n.idType = :type')
                            ->setParameter('type', NationalIdType::NATIONAL_ID)
                            ->orderBy('n.idNumber', $direction);
                        break;
                    default:
                        throw new \InvalidArgumentException('Invalid order by directive '.$name);
                }
            }
        }

        return new Paginator($qbr);
    }
}
