<?php

namespace BeneficiaryBundle\Repository;

/**
 * CountrySpecificRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountrySpecificRepository extends \Doctrine\ORM\EntityRepository
{
    public function findForCriteria(string $countryISO3)
    {
        return $this->findBy(["countryIso3" => $countryISO3]);
    }
}
