<?php

namespace BeneficiaryBundle\Repository;

/**
 * HHMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HHMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
