<?php

namespace BeneficiaryBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
use NewApiBundle\InputType\NationalIdFilterInputType;

/**
 * NationalIdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NationalIdRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByParams(NationalIdFilterInputType $filter): Paginator
    {
        $qbr = $this->createQueryBuilder('n');

        if ($filter) {
            if ($filter->hasIds()) {
                $qbr->andWhere('n.id IN (:ids)')
                    ->setParameter('ids', $filter->getIds());
            }
        }

        return new Paginator($qbr);
    }

    public function findDuplicitiesByCountry(string $type, string $number, string $iso3): array
    {
        return $this->createQueryBuilder('ni')
            ->join('ni.person', 'per')
            ->join('per.beneficiary', 'b')
            ->join('b.household', 'h')
            ->join('h.projects', 'proj')
            ->andWhere('ni.idType = :type')
            ->andWhere('ni.idNumber = :number')
            ->andWhere('proj.iso3 = :iso3')
            ->setParameter('type', $type)
            ->setParameter('number', $number)
            ->setParameter('iso3', $iso3)
            ->getQuery()
            ->getResult();
    }
}
