@startuml

|#AliceBlue|Client|
start
:Import file;
|#LavenderBlush|Server|
if (file error) then (yes)
    |Client|
    - File error
    end
else (no)
    |#Ivory|Cache|
    -Create token state
    -Create folder
    |Server|
    -Missing treatment
    if (Missing) then (yes)
        |Client|
        -Content error
        end
    else (no)
        |Server|
        -Typo Verif
        |Cache|
        -Add new to to_create
        -Add existing to to_update
        |Server|
        if (Typo) then (yes)
            |Client|
            -User input
        else (no)
        endif
        |Server|
        -Typo treatment
        |Cache|
        -Update cache
        |Server|
        -More verification
        if (More) then (yes) 
            |Client|
            -User Input
        else (no)
        endif
        |Server|
        -More treatment
        |Cache|
        -Update to_update
        |Server|
        -Less verification
        if (Less) then (yes) 
            |Client|
            -User Input
        else (no)
        endif
        |Server|
        -Less treatment
        |Cache|
        -Update to_update
        |Server|
        -Duplicate verification
        if (Duplicates) then (yes)
            |Client|
            -User Input
        else (no)
        endif
        |Cache|
        -Update cache
        |Server|
        -Send data
        |Client|
        -Validation
        |Server|
        -Validate treatment
        |Cache|
        -Get to_update
        -Get to_create
        |Server|
        -Update database
        |Client|
        -Display imported data        
endif
stop


@enduml