dh_auditor:
    enabled: true
    timezone: 'UTC'
    providers:
        doctrine:
            storage_services:
                - '@doctrine.orm.default_entity_manager'
            auditing_services:
                - '@doctrine.orm.default_entity_manager'
            table_prefix: 'audit_'
            viewer: true
            ignored_columns:
                - 'createdAt'
