# Description: Sort method arguments to place required parameters before optional parameters.
sortParamsByRequiredFlag: true

# Description: Sort model properties to place required parameters before optional parameters.
sortModelPropertiesByRequiredFlag: true

# Description: Whether to ensure parameter names are unique in an operation (rename parameters that are not).
ensureUniqueParams: true

# Description: boolean, toggles whether unicode identifiers are allowed in names or not, default is false
allowUnicodeIdentifiers: false

# Description: Add form or body parameters to the beginning of the parameter list.
prependFormOrBodyParameters: false

# Description: Set to false for generators with better support for discriminators. (Python, Java, Go, PowerShell, C#have this enabled by default).
# Available Values:
#    true
#         The mapping in the discriminator includes descendent schemas that allOf inherit from self and the discriminator mapping schemas in the OAS document.
#    false
#         The mapping in the discriminator includes any descendent schemas that allOf inherit from self, any oneOf schemas, any anyOf schemas, any x-discriminator-values, and the discriminator mapping schemas in the OAS document AND Codegen validates that oneOf and anyOf schemas contain the required discriminator and throws an error if the discriminator is missing.
legacyDiscriminatorBehavior: true

# Description: If false, the 'additionalProperties' implementation (set to true by default) is compliant with the OAS and JSON schema specifications. If true (default), keep the old (incorrect) behaviour that 'additionalProperties' is set to false by default.
# Available Values:
#    false
#         The 'additionalProperties' implementation is compliant with the OAS and JSON schema specifications.
#    true
#         Keep the old (incorrect) behaviour that 'additionalProperties' is set to false by default.
disallowAdditionalPropertiesIfNotPresent: true

# Description: package for generated models
# modelPackage:

# Description: package for generated api classes
# apiPackage:

# Description: naming convention of variable name, e.g. camelCase.
variableNamingConvention: camelCase

# Description: The main namespace to use for all classes. e.g. Yay\Pets
invokerPackage: Humansis\WebApi

# Description: The main package name for classes. e.g. GeneratedPetstore
packageName: 'HumansisWebApiBundle'

# Description: The directory to serve as source root.
# srcBasePath:

# Description: The version to use in the composer package version field. e.g. 1.2.3
# artifactVersion:

# Description: The vendor name used in the composer package name. The template uses {{composerVendorName}}/{{composerProjectName}} for the composer package name. e.g. yaypets
composerVendorName: 'Humansis'

# Description: The name of the Symfony bundle. The template uses {{bundleName}}
bundleName: 'HumansisWebApiBundle'

# Description: The alias of the Symfony bundle. The template uses {{aliasName}}
# bundleAlias:

# Description: The project name used in the composer package name. The template uses {{composerVendorName}}/{{composerProjectName}} for the composer package name. e.g. petstore-client
composerProjectName: 'WebApiSdk'

# Description: Hides the generation timestamp when files are generated.
hideGenerationTimestamp: true

# Description: Should the generated code be compatible with PHP 5.x?
#phpLegacySupport: false

enablePostProcessFile: false
