parameters:
    environment: '%env(ENVIRONMENT)%'

    database_driver: pdo_mysql
    database_host: '%env(RDS_HOSTNAME)%'
    database_port: '%env(RDS_PORT)%'
    database_name: '%env(RDS_DB_NAME)%'
    database_user: '%env(RDS_USERNAME)%'
    database_password: '%env(RDS_PASSWORD)%'

    mailer_transport: smtp
    mailer_host: email-smtp.eu-west-1.amazonaws.com
    mailer_user: '%env(SES_USERNAME)%'
    mailer_password: '%env(SES_PASSWORD)%'
    mailer_port: 587
    mailer_encryption: tls
    mailer_dsn: '%mailer_transport%://%mailer_user%:%mailer_password%@%mailer_host%:%mailer_port%'

    secret: '%env(SYMFONY_SECRET)%'
    aws_access_key_id: '%env(AWS_ACCESS_KEY)%'
    aws_secret_access_key: '%env(AWS_SECRET_KEY)%'
    aws_s3_region: eu-central-1
    aws_s3_bucket_name: files-testing.bmstaging.info
    humanitarian_secret: '%env(HID_SECRET)%'
    crowdin_api_key: '%env(CROWDIN_API_KEY)%'
    crowdin_project_id: '%env(CROWDIN_PROJECT_ID)%'

    mobile_app_master_key: '%env(MOBILE_MASTER_KEY)%'
    mobile_app_version: '%env(MOBILE_APP_VERSION)%'
    mobile_app_id: '%env(MOBILE_APP_ID)%'

    jwt_passphrase: '%env(JWT_PASSPHRASE)%'

    gelf_server_name: '%env(GELF_SERVER_NAME)%'
    gelf_host: '%env(GELF_HOST)%'
    gelf_port: '%env(GELF_PORT)%'

    #TODO refactor parameters names in whole system
    aws.logs.key: '%env(AWS_LOGS_ACCESS_KEY)%'
    aws.logs.secret: '%env(AWS_LOGS_SECRET_KEY)%'
    aws.logs.region: 'eu-central-1'
    aws.logs.version: 'latest'
    aws.logs.bucket: 'logs.humansis.org'
    aws.logs.folder: 'logs'

    logs.vendorAppPath: 'vendor_app/%environment%/vendor-<<email>>_<<vendorId>>/<<datetime>>/'
    logs.fieldAppPath: 'field_app/%environment%/user-<<email>>_<<userId>>/<<datetime>>/'
    logs.lifetime: 42 #in days. (6 weeks)

    #todo set proper project dns
    sentry.dsn: 'https://7ff5069624384df8bf3d303b551f8453@o1378753.ingest.sentry.io/6690862'

    default_account: admin@example.org
    default_account_encoded_password: '%env(DEFAULT_ACCOUNT_PASSWORD)%'
    default_account_salt: '%env(DEFAULT_ACCOUNT_SALT)%'
