<?php
/**
 * InlineResponse400
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  Humansis\VendorAppApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Humansis Vendor App
 *
 * This is an API documentation for Humansis Vendor App.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace Humansis\VendorAppApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the InlineResponse400 model.
 *
 * @package Humansis\VendorAppApi\Model
 * @author  OpenAPI Generator team
 */
class InlineResponse400 
{
        /**
     * @var Humansis\VendorAppApi\Model\InlineResponse400Errors[]|null
     * @SerializedName("errors")
     * @Assert\All({
     *   @Assert\Type("Humansis\VendorAppApi\Model\InlineResponse400Errors")
     * })
     * @Type("array<Humansis\VendorAppApi\Model\InlineResponse400Errors>")
     */
    protected $errors;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->errors = isset($data['errors']) ? $data['errors'] : null;
    }

    /**
     * Gets errors.
     *
     * @return Humansis\VendorAppApi\Model\InlineResponse400Errors[]|null
     */
    public function getErrors(): ?array
    {
        return $this->errors;
    }

    /**
     * Sets errors.
     *
     * @param Humansis\VendorAppApi\Model\InlineResponse400Errors[]|null $errors
     *
     * @return $this
     */
    public function setErrors(array $errors = null)
    {
        $this->errors = $errors;

        return $this;
    }
}


