services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    TransactionBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: [ 'app.controller' ]

    transaction.transaction_service:
        class: TransactionBundle\Utils\TransactionService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@service_container'

    transaction.default_financial_provider:
        class: TransactionBundle\Utils\Provider\DefaultFinancialProvider
        public: true
        abstract: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@service_container'

    transaction.khm_financial_provider:
        class: TransactionBundle\Utils\Provider\KHMFinancialProvider
        parent: transaction.default_financial_provider
        autowire: false
        autoconfigure: false
        public: true

    TransactionBundle\Mapper\TransactionMapper:
        arguments:
            - "@serializer"
        public: true

    export.distributed_summary.spreadsheet:
        class: TransactionBundle\Export\DistributedSummarySpreadsheetExport
        arguments:
            - '@translator'
            - '@NewApiBundle\Component\Country\Countries'
            - "@=service('doctrine.orm.entity_manager').getRepository('NewApiBundle:DistributedItem')"
        public: true

    export.purchased_summary.spreadsheet:
        class: TransactionBundle\Export\PurchasedSummarySpreadsheetExport
        arguments:
            - '@translator'
            - '@NewApiBundle\Component\Country\Countries'
            - "@=service('doctrine.orm.entity_manager').getRepository('NewApiBundle:PurchasedItem')"
        public: true

    export.spreadsheet:
        class: TransactionBundle\Export\AssistanceSpreadsheetExport
        arguments: [ '@translator', '@NewApiBundle\Component\Smartcard\SmartcardDepositService' ]
        public: true

    TransactionBundle\Export\AssistanceSpreadsheetExport: '@export.spreadsheet'

    export.pdf:
        class: TransactionBundle\Export\AssistancePdfExport
        arguments: [ '@translator', '@pdf_service', '@Twig\Environment' ]
        public: true
