<?php

namespace Repository;

/**
 * CountrySpecificAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountrySpecificAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
