<?php

namespace Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use DTO\NationalIdInfoDTO;
use InputType\NationalIdFilterInputType;

/**
 * NationalIdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NationalIdRepository extends EntityRepository
{
    public function findByParams(NationalIdFilterInputType $filter): Paginator
    {
        $qbr = $this->createQueryBuilder('n');

        if ($filter) {
            if ($filter->hasIds()) {
                $qbr->andWhere('n.id IN (:ids)')
                    ->setParameter('ids', $filter->getIds());
            }
        }

        return new Paginator($qbr);
    }
    public function getNationalIdsInfoByPersonId(int $personId): array
    {
        $qb = $this->createQueryBuilder('n')
            ->select(
                sprintf(
                    'NEW %s(
                    n.idType,
                    n.idNumber
                )',
                    NationalIdInfoDTO::class
                )
            )
            ->where('IDENTITY(n.person) = :personId')
            ->setParameter('personId', $personId);

        $nationalIds = [];

        /** @var NationalIdInfoDTO $nationalIdInfoDTO */
        foreach ($qb->getQuery()->getResult() as $nationalIdInfoDTO) {
            $nationalIds[] = [
                'type' => $nationalIdInfoDTO->getIdType(),
                'number' => $nationalIdInfoDTO->getIdNumber(),
            ];
        }

        return $nationalIds;
    }
}
