<?php

namespace Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Exception\ORMException;
use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Entity\Organization;
use Request\Pagination;

/**
 * OrganizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationRepository extends EntityRepository
{
    public function findByParams(?Pagination $pagination = null): Paginator
    {
        $qb = $this->createQueryBuilder('o');

        if ($pagination) {
            $qb->setMaxResults($pagination->getLimit());
            $qb->setFirstResult($pagination->getOffset());
        }

        return new Paginator($qb);
    }

    /**
     *
     * @throws ORMException
     * @throws OptimisticLockException
     */
    public function save(Organization $organization): void
    {
        $this->_em->persist($organization);
        $this->_em->flush();
    }
}
