<?php

namespace Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Exception\ORMException;
use Doctrine\ORM\OptimisticLockException;
use Entity\UserCountry;

/**
 * UserCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCountryRepository extends EntityRepository
{
    /**
     *
     * @throws ORMException
     * @throws OptimisticLockException
     */
    public function save(UserCountry $userCountry): void
    {
        $this->_em->persist($userCountry);
        $this->_em->flush();
    }
}
