<?php

namespace Repository;

use Doctrine\ORM\EntityNotFoundException;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Entity\Location;
use Entity\Vendor;
use Enum\EnumValueNoFoundException;
use Enum\VendorInvoicingState;
use Generator;
use InputType\VendorFilterInputType;
use InputType\VendorOrderInputType;
use InvalidArgumentException;
use Repository\Helper\TRepositoryHelper;
use Request\Pagination;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Entity\User;

/**
 * VendorRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method findOneByUser(User $user);
 */
class VendorRepository extends EntityRepository
{
    use TRepositoryHelper;

    private ?LocationRepository $locationRepository = null;

    public function setLocationRepository(LocationRepository $locationRepository)
    {
        $this->locationRepository = $locationRepository;
    }

    public function findByCountry($countryISO3)
    {
        $qb = $this->createQueryBuilder('v')
            ->andWhere('v.archived = false')
            ->leftJoin('v.location', 'l');
        $locationRepository = $this->getEntityManager()->getRepository(Location::class);
        $locationRepository->whereCountry($qb, $countryISO3);

        return $qb->getQuery()->getResult();
    }

    /**
     * @throws EnumValueNoFoundException
     */
    public function findByParams(
        ?string $iso3,
        ?VendorFilterInputType $filter = null,
        ?VendorOrderInputType $orderBy = null,
        ?Pagination $pagination = null
    ): Paginator {
        $qb = $this->createQueryBuilder('v')
            ->andWhere('v.archived = 0')
            ->leftJoin('v.location', 'l')
            ->andWhere('l.countryIso3 = :iso3')
            ->setParameter("iso3", $iso3);

        if ($filter) {
            if ($filter->hasIds()) {
                $qb->andWhere('v.id IN (:ids)')
                    ->setParameter('ids', $filter->getIds());
            }
            if ($filter->hasFulltext()) {
                $qb->leftJoin('v.user', 'u');

                $qb->andWhere(
                    '(v.id = :fulltextId OR
                                u.username LIKE :fulltext OR
                                v.vendorNo LIKE :fulltext OR
                                v.contractNo LIKE :fulltext OR
                                v.shop LIKE :fulltext OR
                                v.name LIKE :fulltext OR
                                v.addressNumber LIKE :fulltext OR
                                v.addressPostcode LIKE :fulltext OR
                                v.addressStreet LIKE :fulltext OR
                                l.name LIKE :fulltext)'
                )
                    ->setParameter('fulltextId', $filter->getFulltext())
                    ->setParameter('fulltext', '%' . $filter->getFulltext() . '%');
            }

            $locations = [];

            if ($filter->hasLocations()) {
                foreach ($filter->getLocations() as $locationKey => $locationId) {
                    /** @var Location|null $location */
                    $location = $this->locationRepository->find($locationId);
                    if (is_null($location)) {
                        throw new NotFoundHttpException("Location $locationId was not found");
                    }
                    $locations = array_unique(
                        array_merge(
                            $locations,
                            iterator_to_array($this->getChildrenLocationIdListByLocation($location))
                        ),
                        SORT_REGULAR
                    );
                }

                if (count($locations) > 0) {
                    $qb->andWhere($qb->expr()->in('v.location', ':locations'))
                        ->setParameter('locations', $locations);
                }
            }

            if ($filter->hasInvoicing()) {
                switch ($filter->getInvoicing()) {
                    case VendorInvoicingState::INVOICED:
                        $qb->leftJoin('v.preliminaryInvoices', 'pre');
                        $qb->andHaving('count(pre.id) = 0');
                        break;
                    case VendorInvoicingState::TO_REDEEM:
                        $qb->innerJoin('v.preliminaryInvoices', 'pre');
                        $qb->andHaving('MAX(pre.isRedeemable) = 1');
                        break;
                    case VendorInvoicingState::SYNC_REQUIRED:
                        $qb->innerJoin('v.preliminaryInvoices', 'pre');
                        $qb->andHaving('MAX(pre.isRedeemable) = 0');
                }
                $qb->addGroupBy('pre.isRedeemable', 'v.id');
            }
        }

        if ($pagination) {
            $qb->setMaxResults($pagination->getLimit());
            $qb->setFirstResult($pagination->getOffset());
        }

        if ($orderBy) {
            foreach ($orderBy->toArray() as $name => $direction) {
                switch ($name) {
                    case VendorOrderInputType::SORT_BY_ID:
                        $qb->orderBy('v.id', $direction);
                        break;
                    case VendorOrderInputType::SORT_BY_NAME:
                        $qb->orderBy('v.name', $direction);
                        break;
                    case VendorOrderInputType::SORT_BY_SHOP:
                        $qb->orderBy('v.shop', $direction);
                        break;
                    case VendorOrderInputType::SORT_BY_USERNAME:
                        if (!in_array('u', $qb->getAllAliases())) {
                            $qb->leftJoin('v.user', 'u');
                        }

                        $qb->orderBy('u.username', $direction);
                        break;
                    case VendorOrderInputType::SORT_BY_ADDRESS_STREET:
                        $qb->orderBy('v.addressStreet', $direction);
                        break;
                    case VendorOrderInputType::SORT_BY_ADDRESS_NUMBER:
                        $qb->orderBy('v.addressNumber', $direction);
                        break;
                    case VendorOrderInputType::SORT_BY_ADDRESS_POSTCODE:
                        $qb->orderBy('v.addressPostcode', $direction);
                        break;
                    case VendorOrderInputType::SORT_BY_LOCATION:
                        $qb->addOrderBy('l.name', $direction);

                        break;
                    default:
                        throw new InvalidArgumentException('Invalid order by directive ' . $name);
                }
            }
        }

        return new Paginator($qb);
    }

    public function getVendorsPaginatorByEntityRoot(array $vendors, Pagination $pagination): Paginator
    {
        $qb = $this->createQueryBuilder('v');
        $qb->where('v IN (:vendors)')
            ->setParameter('vendors', $vendors);
        $qb->setFirstResult($pagination->getOffset());
        $qb->setMaxResults($pagination->getLimit());

        return new Paginator($qb);
    }

    private function getChildrenLocationIdListByLocation(Location $location): Generator
    {
        $children = $this->locationRepository->getChildrenLocations($location);
        foreach ($children as $childKey => $child) {
            yield $child->getId();
        }
    }

    /**
     * @throws EntityNotFoundException
     */
    public function getById(int $vendorId): Vendor
    {
        $vendor = $this->find($vendorId);

        if ($vendor === null) {
            throw EntityNotFoundException::fromClassNameAndIdentifier(Vendor::class, (array) $vendorId);
        }

        return $vendor;
    }
}
