<?php

namespace UserBundle\Repository;

use UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function edit(User $user, array $arrayData)
    {
        if (empty($arrayData)) {
            return $user;
        }

        $qb = $this->_em->createQueryBuilder();
        $builder = $qb->update("UserBundle:User", 'u');

        foreach ($arrayData as $column => $value) {
            $builder->set("u.$column", $qb->expr()->literal($value));
        }

        $builder->andWhere("u.id = :user")
        ->setParameter('user', $user->getId());

        return $builder->getQuery()->execute();
    }
}
