<?php

namespace UserBundle\Repository;

/**
 * UserCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
