parameters:
        import.invalidFilesDirectory: '%kernel.project_dir%/var/imports/invalid'
        import.uploadedFilesDirectory: '%kernel.project_dir%/var/imports/uploaded'
        import.maxFileSizeToLoad: 1 #in MB

        aws.logs.key: 'AKIAYYVDSYNUDIO7EFGL'
        aws.logs.secret: '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'
        aws.logs.region: 'eu-central-1'
        aws.logs.version: 'latest'
        aws.logs.bucket: 'logs.humansis.org'
        aws.logs.folder: 'logs'
