parameters:
        import.invalidFilesDirectory: '%kernel.project_dir%/var/imports/invalid'
        import.uploadedFilesDirectory: '%kernel.project_dir%/var/imports/uploaded'
        import.maxFileSizeToLoad: 1 #in MB
        import.batch_size: 200

        aws.logs.key: '%env(AWS_LOGS_ACCESS_KEY)%'
        aws.logs.secret: '%env(AWS_LOGS_SECRET_KEY)%'
        aws.logs.region: 'eu-central-1'
        aws.logs.version: 'latest'
        aws.logs.bucket: 'logs.humansis.org'
        aws.logs.folder: 'logs'
