framework:
  workflows:
    reliefPackage:
      type: 'state_machine'
      marking_store:
        type: 'single_state'
        arguments:
          - 'state'
      supports:
        - NewApiBundle\Entity\ReliefPackage
      initial_marking: !php/const NewApiBundle\Enum\ReliefPackageState::TO_DISTRIBUTE
      places:
        - !php/const NewApiBundle\Enum\ReliefPackageState::TO_DISTRIBUTE
        - !php/const NewApiBundle\Enum\ReliefPackageState::DISTRIBUTION_IN_PROGRESS
        - !php/const NewApiBundle\Enum\ReliefPackageState::DISTRIBUTED
        - !php/const NewApiBundle\Enum\ReliefPackageState::EXPIRED
        - !php/const NewApiBundle\Enum\ReliefPackageState::CANCELED
      transitions:
        !php/const NewApiBundle\Workflow\ReliefPackageTransitions::START_PARTIAL_DISTRIBUTION:
          from: !php/const NewApiBundle\Enum\ReliefPackageState::TO_DISTRIBUTE
          to: !php/const NewApiBundle\Enum\ReliefPackageState::DISTRIBUTION_IN_PROGRESS
        !php/const NewApiBundle\Workflow\ReliefPackageTransitions::FINISH_PARTIAL_DISTRIBUTION:
          from: !php/const NewApiBundle\Enum\ReliefPackageState::DISTRIBUTION_IN_PROGRESS
          to: !php/const NewApiBundle\Enum\ReliefPackageState::DISTRIBUTED
        !php/const NewApiBundle\Workflow\ReliefPackageTransitions::DISTRIBUTE:
          from: !php/const NewApiBundle\Enum\ReliefPackageState::TO_DISTRIBUTE
          to: !php/const NewApiBundle\Enum\ReliefPackageState::DISTRIBUTED
        !php/const NewApiBundle\Workflow\ReliefPackageTransitions::EXPIRE:
          from: !php/const NewApiBundle\Enum\ReliefPackageState::TO_DISTRIBUTE
          to: !php/const NewApiBundle\Enum\ReliefPackageState::EXPIRED
        !php/const NewApiBundle\Workflow\ReliefPackageTransitions::CANCEL:
          from: !php/const NewApiBundle\Enum\ReliefPackageState::TO_DISTRIBUTE
          to: !php/const NewApiBundle\Enum\ReliefPackageState::CANCELED
    synchronizationBatch:
      type: 'state_machine'
      marking_store:
        type: 'single_state'
        arguments:
          - 'state'
      supports:
        - NewApiBundle\Entity\SynchronizationBatch
      initial_marking: !php/const NewApiBundle\Enum\SynchronizationBatchState::UPLOADED
      places:
        - !php/const NewApiBundle\Enum\SynchronizationBatchState::UPLOADED
        - !php/const NewApiBundle\Enum\SynchronizationBatchState::CORRECT
        - !php/const NewApiBundle\Enum\SynchronizationBatchState::INCORRECT
        - !php/const NewApiBundle\Enum\SynchronizationBatchState::ARCHIVED
      transitions:
        !php/const NewApiBundle\Workflow\SynchronizationBatchTransitions::COMPLETE_VALIDATION:
          from:
            - !php/const NewApiBundle\Enum\SynchronizationBatchState::UPLOADED
          to:
            - !php/const NewApiBundle\Enum\SynchronizationBatchState::CORRECT
        !php/const NewApiBundle\Workflow\SynchronizationBatchTransitions::FAIL_VALIDATION:
          from:
            - !php/const NewApiBundle\Enum\SynchronizationBatchState::UPLOADED
          to:
            - !php/const NewApiBundle\Enum\SynchronizationBatchState::INCORRECT
        !php/const NewApiBundle\Workflow\SynchronizationBatchTransitions::ARCHIVE:
          from:
            - !php/const NewApiBundle\Enum\SynchronizationBatchState::UPLOADED
            - !php/const NewApiBundle\Enum\SynchronizationBatchState::CORRECT
            - !php/const NewApiBundle\Enum\SynchronizationBatchState::INCORRECT
          to: !php/const NewApiBundle\Enum\SynchronizationBatchState::ARCHIVED

    import:
      type: 'state_machine'
      marking_store:
        type: 'method'
        property: 'state'
      supports:
        - NewApiBundle\Component\Import\Entity\Import
      initial_marking: !php/const NewApiBundle\Component\Import\Enum\State::NEW
      places:
        - !php/const NewApiBundle\Component\Import\Enum\State::NEW
        - !php/const NewApiBundle\Component\Import\Enum\State::INTEGRITY_CHECKING
        - !php/const NewApiBundle\Component\Import\Enum\State::INTEGRITY_CHECK_CORRECT
        - !php/const NewApiBundle\Component\Import\Enum\State::INTEGRITY_CHECK_FAILED
        - !php/const NewApiBundle\Component\Import\Enum\State::IDENTITY_CHECKING
        - !php/const NewApiBundle\Component\Import\Enum\State::IDENTITY_CHECK_CORRECT
        - !php/const NewApiBundle\Component\Import\Enum\State::IDENTITY_CHECK_FAILED
        - !php/const NewApiBundle\Component\Import\Enum\State::SIMILARITY_CHECKING
        - !php/const NewApiBundle\Component\Import\Enum\State::SIMILARITY_CHECK_CORRECT
        - !php/const NewApiBundle\Component\Import\Enum\State::SIMILARITY_CHECK_FAILED
        - !php/const NewApiBundle\Component\Import\Enum\State::IMPORTING
        - !php/const NewApiBundle\Component\Import\Enum\State::FINISHED
        - !php/const NewApiBundle\Component\Import\Enum\State::CANCELED
      transitions:

        # INTEGRITY
        !php/const NewApiBundle\Component\Import\Enum\Transitions::CHECK_INTEGRITY:
          from: !php/const NewApiBundle\Component\Import\Enum\State::NEW
          to: !php/const NewApiBundle\Component\Import\Enum\State::INTEGRITY_CHECKING
        !php/const NewApiBundle\Component\Import\Enum\Transitions::COMPLETE_INTEGRITY:
          from: !php/const NewApiBundle\Component\Import\Enum\State::INTEGRITY_CHECKING
          to: !php/const NewApiBundle\Component\Import\Enum\State::INTEGRITY_CHECK_CORRECT
        !php/const NewApiBundle\Component\Import\Enum\Transitions::FAIL_INTEGRITY:
          from: !php/const NewApiBundle\Component\Import\Enum\State::INTEGRITY_CHECKING
          to: !php/const NewApiBundle\Component\Import\Enum\State::INTEGRITY_CHECK_FAILED
        !php/const NewApiBundle\Component\Import\Enum\Transitions::REDO_INTEGRITY:
          from: !php/const NewApiBundle\Component\Import\Enum\State::INTEGRITY_CHECKING
          to: !php/const NewApiBundle\Component\Import\Enum\State::INTEGRITY_CHECKING

        # IDENTITY
        !php/const NewApiBundle\Component\Import\Enum\Transitions::CHECK_IDENTITY:
          from:
            - !php/const NewApiBundle\Component\Import\Enum\State::INTEGRITY_CHECK_CORRECT
            - !php/const NewApiBundle\Component\Import\Enum\State::IDENTITY_CHECKING
            - !php/const NewApiBundle\Component\Import\Enum\State::IDENTITY_CHECK_CORRECT
          to: !php/const NewApiBundle\Component\Import\Enum\State::IDENTITY_CHECKING
        !php/const NewApiBundle\Component\Import\Enum\Transitions::COMPLETE_IDENTITY:
          from: !php/const NewApiBundle\Component\Import\Enum\State::IDENTITY_CHECKING
          to: !php/const NewApiBundle\Component\Import\Enum\State::IDENTITY_CHECK_CORRECT
        !php/const NewApiBundle\Component\Import\Enum\Transitions::FAIL_IDENTITY:
          from: !php/const NewApiBundle\Component\Import\Enum\State::IDENTITY_CHECKING
          to: !php/const NewApiBundle\Component\Import\Enum\State::IDENTITY_CHECK_FAILED
        !php/const NewApiBundle\Component\Import\Enum\Transitions::REDO_IDENTITY:
          from: !php/const NewApiBundle\Component\Import\Enum\State::IDENTITY_CHECKING
          to: !php/const NewApiBundle\Component\Import\Enum\State::IDENTITY_CHECKING
        !php/const NewApiBundle\Component\Import\Enum\Transitions::RESOLVE_IDENTITY_DUPLICITIES:
          from: !php/const NewApiBundle\Component\Import\Enum\State::IDENTITY_CHECK_FAILED
          to: !php/const NewApiBundle\Component\Import\Enum\State::IDENTITY_CHECK_CORRECT

        # SIMILARITY
        !php/const NewApiBundle\Component\Import\Enum\Transitions::CHECK_SIMILARITY:
          from: !php/const NewApiBundle\Component\Import\Enum\State::IDENTITY_CHECK_CORRECT
          to: !php/const NewApiBundle\Component\Import\Enum\State::SIMILARITY_CHECKING
        !php/const NewApiBundle\Component\Import\Enum\Transitions::COMPLETE_SIMILARITY:
          from: !php/const NewApiBundle\Component\Import\Enum\State::SIMILARITY_CHECKING
          to: !php/const NewApiBundle\Component\Import\Enum\State::SIMILARITY_CHECK_CORRECT
        !php/const NewApiBundle\Component\Import\Enum\Transitions::FAIL_SIMILARITY:
          from: !php/const NewApiBundle\Component\Import\Enum\State::SIMILARITY_CHECKING
          to: !php/const NewApiBundle\Component\Import\Enum\State::SIMILARITY_CHECK_FAILED
        !php/const NewApiBundle\Component\Import\Enum\Transitions::REDO_SIMILARITY:
          from: !php/const NewApiBundle\Component\Import\Enum\State::SIMILARITY_CHECKING
          to: !php/const NewApiBundle\Component\Import\Enum\State::SIMILARITY_CHECKING
        !php/const NewApiBundle\Component\Import\Enum\Transitions::RESOLVE_SIMILARITY_DUPLICITIES:
          from: !php/const NewApiBundle\Component\Import\Enum\State::SIMILARITY_CHECK_FAILED
          to: !php/const NewApiBundle\Component\Import\Enum\State::SIMILARITY_CHECK_CORRECT

        !php/const NewApiBundle\Component\Import\Enum\Transitions::RESET:
          from:
            - !php/const NewApiBundle\Component\Import\Enum\State::IDENTITY_CHECKING
            - !php/const NewApiBundle\Component\Import\Enum\State::IDENTITY_CHECK_CORRECT
            - !php/const NewApiBundle\Component\Import\Enum\State::SIMILARITY_CHECKING
            - !php/const NewApiBundle\Component\Import\Enum\State::SIMILARITY_CHECK_CORRECT
            - !php/const NewApiBundle\Component\Import\Enum\State::SIMILARITY_CHECK_FAILED
          to: !php/const NewApiBundle\Component\Import\Enum\State::IDENTITY_CHECKING
        !php/const NewApiBundle\Component\Import\Enum\Transitions::IMPORT:
          from: !php/const NewApiBundle\Component\Import\Enum\State::SIMILARITY_CHECK_CORRECT
          to: !php/const NewApiBundle\Component\Import\Enum\State::IMPORTING
        !php/const NewApiBundle\Component\Import\Enum\Transitions::FINISH:
          from: !php/const NewApiBundle\Component\Import\Enum\State::IMPORTING
          to: !php/const NewApiBundle\Component\Import\Enum\State::FINISHED
        !php/const NewApiBundle\Component\Import\Enum\Transitions::CANCEL:
          from:
            - !php/const NewApiBundle\Component\Import\Enum\State::NEW
            - !php/const NewApiBundle\Component\Import\Enum\State::INTEGRITY_CHECKING
            - !php/const NewApiBundle\Component\Import\Enum\State::INTEGRITY_CHECK_CORRECT
            - !php/const NewApiBundle\Component\Import\Enum\State::IDENTITY_CHECKING
            - !php/const NewApiBundle\Component\Import\Enum\State::IDENTITY_CHECK_CORRECT
            - !php/const NewApiBundle\Component\Import\Enum\State::SIMILARITY_CHECKING
            - !php/const NewApiBundle\Component\Import\Enum\State::SIMILARITY_CHECK_CORRECT
          to: !php/const NewApiBundle\Component\Import\Enum\State::CANCELED

    import_queue:
      type: 'state_machine'
      marking_store:
        type: 'method'
        property: 'state'
      supports:
        - NewApiBundle\Component\Import\Entity\Queue
      initial_marking: !php/const NewApiBundle\Component\Import\Enum\QueueState::NEW
      places:
        - !php/const NewApiBundle\Component\Import\Enum\QueueState::NEW
        - !php/const NewApiBundle\Component\Import\Enum\QueueState::VALID
        - !php/const NewApiBundle\Component\Import\Enum\QueueState::INVALID
        - !php/const NewApiBundle\Component\Import\Enum\QueueState::INVALID_EXPORTED
        - !php/const NewApiBundle\Component\Import\Enum\QueueState::IDENTITY_CANDIDATE
        - !php/const NewApiBundle\Component\Import\Enum\QueueState::UNIQUE_CANDIDATE
        - !php/const NewApiBundle\Component\Import\Enum\QueueState::SIMILARITY_CANDIDATE
        - !php/const NewApiBundle\Component\Import\Enum\QueueState::TO_CREATE
        - !php/const NewApiBundle\Component\Import\Enum\QueueState::TO_UPDATE
        - !php/const NewApiBundle\Component\Import\Enum\QueueState::TO_LINK
        - !php/const NewApiBundle\Component\Import\Enum\QueueState::TO_IGNORE
        - !php/const NewApiBundle\Component\Import\Enum\QueueState::CREATED
        - !php/const NewApiBundle\Component\Import\Enum\QueueState::UPDATED
        - !php/const NewApiBundle\Component\Import\Enum\QueueState::LINKED
      transitions:

        # integrity
        !php/const NewApiBundle\Component\Import\Enum\QueueTransitions::VALIDATE:
          from: !php/const NewApiBundle\Component\Import\Enum\QueueState::NEW
          to: !php/const NewApiBundle\Component\Import\Enum\QueueState::VALID
        !php/const NewApiBundle\Component\Import\Enum\QueueTransitions::INVALIDATE:
          from: !php/const NewApiBundle\Component\Import\Enum\QueueState::NEW
          to: !php/const NewApiBundle\Component\Import\Enum\QueueState::INVALID

        # identity
        !php/const NewApiBundle\Component\Import\Enum\QueueTransitions::IDENTITY_CANDIDATE:
          from: !php/const NewApiBundle\Component\Import\Enum\QueueState::VALID
          to: !php/const NewApiBundle\Component\Import\Enum\QueueState::IDENTITY_CANDIDATE
        !php/const NewApiBundle\Component\Import\Enum\QueueTransitions::UNIQUE_CANDIDATE:
          from: !php/const NewApiBundle\Component\Import\Enum\QueueState::VALID
          to: !php/const NewApiBundle\Component\Import\Enum\QueueState::UNIQUE_CANDIDATE

        # similarity
        !php/const NewApiBundle\Component\Import\Enum\QueueTransitions::SIMILARITY_CANDIDATE:
          from: !php/const NewApiBundle\Component\Import\Enum\QueueState::UNIQUE_CANDIDATE
          to: !php/const NewApiBundle\Component\Import\Enum\QueueState::SIMILARITY_CANDIDATE

        # duplicity resolving
        !php/const NewApiBundle\Component\Import\Enum\QueueTransitions::TO_CREATE:
          from: !php/const NewApiBundle\Component\Import\Enum\QueueState::UNIQUE_CANDIDATE
          to: !php/const NewApiBundle\Component\Import\Enum\QueueState::TO_CREATE
        !php/const NewApiBundle\Component\Import\Enum\QueueTransitions::TO_UPDATE:
          from:
            - !php/const NewApiBundle\Component\Import\Enum\QueueState::IDENTITY_CANDIDATE
            - !php/const NewApiBundle\Component\Import\Enum\QueueState::SIMILARITY_CANDIDATE
          to: !php/const NewApiBundle\Component\Import\Enum\QueueState::TO_UPDATE
        # to_ignore = to_link ... unify the states in the future
        !php/const NewApiBundle\Component\Import\Enum\QueueTransitions::TO_IGNORE:
          from:
            - !php/const NewApiBundle\Component\Import\Enum\QueueState::IDENTITY_CANDIDATE
            - !php/const NewApiBundle\Component\Import\Enum\QueueState::SIMILARITY_CANDIDATE
          to: !php/const NewApiBundle\Component\Import\Enum\QueueState::TO_IGNORE
        !php/const NewApiBundle\Component\Import\Enum\QueueTransitions::TO_LINK:
          from:
            - !php/const NewApiBundle\Component\Import\Enum\QueueState::IDENTITY_CANDIDATE
            - !php/const NewApiBundle\Component\Import\Enum\QueueState::SIMILARITY_CANDIDATE
          to: !php/const NewApiBundle\Component\Import\Enum\QueueState::TO_IGNORE

        # reset
        !php/const NewApiBundle\Component\Import\Enum\QueueTransitions::RESET:
          from:
            - !php/const NewApiBundle\Component\Import\Enum\QueueState::TO_CREATE
            - !php/const NewApiBundle\Component\Import\Enum\QueueState::TO_UPDATE
            - !php/const NewApiBundle\Component\Import\Enum\QueueState::TO_IGNORE
            - !php/const NewApiBundle\Component\Import\Enum\QueueState::TO_LINK
          to: !php/const NewApiBundle\Component\Import\Enum\QueueState::VALID

        # finish
        !php/const NewApiBundle\Component\Import\Enum\QueueTransitions::CREATE:
          from: !php/const NewApiBundle\Component\Import\Enum\QueueState::TO_CREATE
          to: !php/const NewApiBundle\Component\Import\Enum\QueueState::CREATED
        !php/const NewApiBundle\Component\Import\Enum\QueueTransitions::UPDATE:
          from: !php/const NewApiBundle\Component\Import\Enum\QueueState::TO_UPDATE
          to: !php/const NewApiBundle\Component\Import\Enum\QueueState::UPDATED
        !php/const NewApiBundle\Component\Import\Enum\QueueTransitions::LINK:
          from:
            - !php/const NewApiBundle\Component\Import\Enum\QueueState::TO_IGNORE
            - !php/const NewApiBundle\Component\Import\Enum\QueueState::TO_LINK
          to: !php/const NewApiBundle\Component\Import\Enum\QueueState::LINKED

