framework:
  workflows:
    reliefPackage:
      type: 'state_machine'
      marking_store:
        type: 'single_state'
        arguments:
          - 'state'
      supports:
        - NewApiBundle\Entity\ReliefPackage
      initial_marking: !php/const NewApiBundle\Enum\ReliefPackageState::TO_DISTRIBUTE
      places:
        - !php/const NewApiBundle\Enum\ReliefPackageState::TO_DISTRIBUTE
        - !php/const NewApiBundle\Enum\ReliefPackageState::DISTRIBUTION_IN_PROGRESS
        - !php/const NewApiBundle\Enum\ReliefPackageState::DISTRIBUTED
        - !php/const NewApiBundle\Enum\ReliefPackageState::EXPIRED
        - !php/const NewApiBundle\Enum\ReliefPackageState::CANCELED
      transitions:
        !php/const NewApiBundle\Workflow\ReliefPackageTransitions::START_PARTIAL_DISTRIBUTION:
          from: !php/const NewApiBundle\Enum\ReliefPackageState::TO_DISTRIBUTE
          to: !php/const NewApiBundle\Enum\ReliefPackageState::DISTRIBUTION_IN_PROGRESS
        !php/const NewApiBundle\Workflow\ReliefPackageTransitions::FINISH_PARTIAL_DISTRIBUTION:
          from: !php/const NewApiBundle\Enum\ReliefPackageState::DISTRIBUTION_IN_PROGRESS
          to: !php/const NewApiBundle\Enum\ReliefPackageState::DISTRIBUTED
        !php/const NewApiBundle\Workflow\ReliefPackageTransitions::DISTRIBUTE:
          from: !php/const NewApiBundle\Enum\ReliefPackageState::TO_DISTRIBUTE
          to: !php/const NewApiBundle\Enum\ReliefPackageState::DISTRIBUTED
        !php/const NewApiBundle\Workflow\ReliefPackageTransitions::EXPIRE:
          from: !php/const NewApiBundle\Enum\ReliefPackageState::TO_DISTRIBUTE
          to: !php/const NewApiBundle\Enum\ReliefPackageState::EXPIRED
        !php/const NewApiBundle\Workflow\ReliefPackageTransitions::CANCEL:
          from: !php/const NewApiBundle\Enum\ReliefPackageState::TO_DISTRIBUTE
          to: !php/const NewApiBundle\Enum\ReliefPackageState::CANCELED

    import:
      type: 'state_machine'
      marking_store:
        type: 'method'
        property: 'state'
      supports:
        - NewApiBundle\Entity\Import
      initial_marking: !php/const NewApiBundle\Enum\ImportState::NEW
      places:
        - !php/const NewApiBundle\Enum\ImportState::NEW
        - !php/const NewApiBundle\Enum\ImportState::INTEGRITY_CHECKING
        - !php/const NewApiBundle\Enum\ImportState::INTEGRITY_CHECK_CORRECT
        - !php/const NewApiBundle\Enum\ImportState::INTEGRITY_CHECK_FAILED
        - !php/const NewApiBundle\Enum\ImportState::IDENTITY_CHECKING
        - !php/const NewApiBundle\Enum\ImportState::IDENTITY_CHECK_CORRECT
        - !php/const NewApiBundle\Enum\ImportState::IDENTITY_CHECK_FAILED
        - !php/const NewApiBundle\Enum\ImportState::SIMILARITY_CHECKING
        - !php/const NewApiBundle\Enum\ImportState::SIMILARITY_CHECK_CORRECT
        - !php/const NewApiBundle\Enum\ImportState::SIMILARITY_CHECK_FAILED
        - !php/const NewApiBundle\Enum\ImportState::IMPORTING
        - !php/const NewApiBundle\Enum\ImportState::FINISHED
        - !php/const NewApiBundle\Enum\ImportState::CANCELED
      transitions:

        # INTEGRITY
        !php/const NewApiBundle\Workflow\ImportTransitions::CHECK_INTEGRITY:
          from: !php/const NewApiBundle\Enum\ImportState::NEW
          to: !php/const NewApiBundle\Enum\ImportState::INTEGRITY_CHECKING
        !php/const NewApiBundle\Workflow\ImportTransitions::COMPLETE_INTEGRITY:
          from: !php/const NewApiBundle\Enum\ImportState::INTEGRITY_CHECKING
          to: !php/const NewApiBundle\Enum\ImportState::INTEGRITY_CHECK_CORRECT
        !php/const NewApiBundle\Workflow\ImportTransitions::FAIL_INTEGRITY:
          from: !php/const NewApiBundle\Enum\ImportState::INTEGRITY_CHECKING
          to: !php/const NewApiBundle\Enum\ImportState::INTEGRITY_CHECK_FAILED
        !php/const NewApiBundle\Workflow\ImportTransitions::REDO_INTEGRITY:
          from: !php/const NewApiBundle\Enum\ImportState::INTEGRITY_CHECKING
          to: !php/const NewApiBundle\Enum\ImportState::INTEGRITY_CHECKING

        # IDENTITY
        !php/const NewApiBundle\Workflow\ImportTransitions::CHECK_IDENTITY:
          from:
            - !php/const NewApiBundle\Enum\ImportState::INTEGRITY_CHECK_CORRECT
            - !php/const NewApiBundle\Enum\ImportState::IDENTITY_CHECKING
            - !php/const NewApiBundle\Enum\ImportState::IDENTITY_CHECK_CORRECT
          to: !php/const NewApiBundle\Enum\ImportState::IDENTITY_CHECKING
        !php/const NewApiBundle\Workflow\ImportTransitions::COMPLETE_IDENTITY:
          from: !php/const NewApiBundle\Enum\ImportState::IDENTITY_CHECKING
          to: !php/const NewApiBundle\Enum\ImportState::IDENTITY_CHECK_CORRECT
        !php/const NewApiBundle\Workflow\ImportTransitions::FAIL_IDENTITY:
          from: !php/const NewApiBundle\Enum\ImportState::IDENTITY_CHECKING
          to: !php/const NewApiBundle\Enum\ImportState::IDENTITY_CHECK_FAILED
        !php/const NewApiBundle\Workflow\ImportTransitions::REDO_IDENTITY:
          from: !php/const NewApiBundle\Enum\ImportState::IDENTITY_CHECKING
          to: !php/const NewApiBundle\Enum\ImportState::IDENTITY_CHECKING
        !php/const NewApiBundle\Workflow\ImportTransitions::RESOLVE_IDENTITY_DUPLICITIES:
          from: !php/const NewApiBundle\Enum\ImportState::IDENTITY_CHECK_FAILED
          to: !php/const NewApiBundle\Enum\ImportState::IDENTITY_CHECK_CORRECT

        # SIMILARITY
        !php/const NewApiBundle\Workflow\ImportTransitions::CHECK_SIMILARITY:
          from: !php/const NewApiBundle\Enum\ImportState::IDENTITY_CHECK_CORRECT
          to: !php/const NewApiBundle\Enum\ImportState::SIMILARITY_CHECKING
        !php/const NewApiBundle\Workflow\ImportTransitions::COMPLETE_SIMILARITY:
          from: !php/const NewApiBundle\Enum\ImportState::SIMILARITY_CHECKING
          to: !php/const NewApiBundle\Enum\ImportState::SIMILARITY_CHECK_CORRECT
        !php/const NewApiBundle\Workflow\ImportTransitions::FAIL_SIMILARITY:
          from: !php/const NewApiBundle\Enum\ImportState::SIMILARITY_CHECKING
          to: !php/const NewApiBundle\Enum\ImportState::SIMILARITY_CHECK_FAILED
        !php/const NewApiBundle\Workflow\ImportTransitions::REDO_SIMILARITY:
          from: !php/const NewApiBundle\Enum\ImportState::SIMILARITY_CHECKING
          to: !php/const NewApiBundle\Enum\ImportState::SIMILARITY_CHECKING
        !php/const NewApiBundle\Workflow\ImportTransitions::RESOLVE_SIMILARITY_DUPLICITIES:
          from: !php/const NewApiBundle\Enum\ImportState::SIMILARITY_CHECK_FAILED
          to: !php/const NewApiBundle\Enum\ImportState::SIMILARITY_CHECK_CORRECT

        !php/const NewApiBundle\Workflow\ImportTransitions::RESET:
          from:
            - !php/const NewApiBundle\Enum\ImportState::IDENTITY_CHECKING
            - !php/const NewApiBundle\Enum\ImportState::IDENTITY_CHECK_CORRECT
            - !php/const NewApiBundle\Enum\ImportState::SIMILARITY_CHECKING
            - !php/const NewApiBundle\Enum\ImportState::SIMILARITY_CHECK_CORRECT
            - !php/const NewApiBundle\Enum\ImportState::SIMILARITY_CHECK_FAILED
          to: !php/const NewApiBundle\Enum\ImportState::IDENTITY_CHECKING
        !php/const NewApiBundle\Workflow\ImportTransitions::IMPORT:
          from: !php/const NewApiBundle\Enum\ImportState::SIMILARITY_CHECK_CORRECT
          to: !php/const NewApiBundle\Enum\ImportState::IMPORTING
        !php/const NewApiBundle\Workflow\ImportTransitions::FINISH:
          from: !php/const NewApiBundle\Enum\ImportState::IMPORTING
          to: !php/const NewApiBundle\Enum\ImportState::FINISHED
        !php/const NewApiBundle\Workflow\ImportTransitions::CANCEL:
          from:
            - !php/const NewApiBundle\Enum\ImportState::NEW
            - !php/const NewApiBundle\Enum\ImportState::INTEGRITY_CHECKING
            - !php/const NewApiBundle\Enum\ImportState::INTEGRITY_CHECK_CORRECT
            - !php/const NewApiBundle\Enum\ImportState::IDENTITY_CHECKING
            - !php/const NewApiBundle\Enum\ImportState::IDENTITY_CHECK_CORRECT
            - !php/const NewApiBundle\Enum\ImportState::SIMILARITY_CHECKING
            - !php/const NewApiBundle\Enum\ImportState::SIMILARITY_CHECK_CORRECT
          to: !php/const NewApiBundle\Enum\ImportState::CANCELED

    import_queue:
      type: 'state_machine'
      marking_store:
        type: 'method'
        property: 'state'
      supports:
        - NewApiBundle\Entity\ImportQueue
      initial_marking: !php/const NewApiBundle\Enum\ImportQueueState::NEW
      places:
        - !php/const NewApiBundle\Enum\ImportQueueState::NEW
        - !php/const NewApiBundle\Enum\ImportQueueState::VALID
        - !php/const NewApiBundle\Enum\ImportQueueState::INVALID
        - !php/const NewApiBundle\Enum\ImportQueueState::INVALID_EXPORTED
        - !php/const NewApiBundle\Enum\ImportQueueState::SUSPICIOUS
        - !php/const NewApiBundle\Enum\ImportQueueState::TO_CREATE
        - !php/const NewApiBundle\Enum\ImportQueueState::TO_UPDATE
        - !php/const NewApiBundle\Enum\ImportQueueState::TO_LINK
        - !php/const NewApiBundle\Enum\ImportQueueState::TO_IGNORE
      transitions:
        !php/const NewApiBundle\Workflow\ImportQueueTransitions::VALIDATE:
          from:
            - !php/const NewApiBundle\Enum\ImportQueueState::NEW
            - !php/const NewApiBundle\Enum\ImportQueueState::SUSPICIOUS
            - !php/const NewApiBundle\Enum\ImportQueueState::TO_CREATE
          to: !php/const NewApiBundle\Enum\ImportQueueState::VALID
        !php/const NewApiBundle\Workflow\ImportQueueTransitions::INVALIDATE:
          from: !php/const NewApiBundle\Enum\ImportQueueState::NEW
          to: !php/const NewApiBundle\Enum\ImportQueueState::INVALID
        !php/const NewApiBundle\Workflow\ImportQueueTransitions::SUSPICIOUS:
          from: !php/const NewApiBundle\Enum\ImportQueueState::VALID
          to: !php/const NewApiBundle\Enum\ImportQueueState::SUSPICIOUS
        !php/const NewApiBundle\Workflow\ImportQueueTransitions::TO_CREATE:
          from: !php/const NewApiBundle\Enum\ImportQueueState::VALID
          to: !php/const NewApiBundle\Enum\ImportQueueState::TO_CREATE
        !php/const NewApiBundle\Workflow\ImportQueueTransitions::TO_UPDATE:
          from: !php/const NewApiBundle\Enum\ImportQueueState::SUSPICIOUS
          to: !php/const NewApiBundle\Enum\ImportQueueState::TO_UPDATE
        !php/const NewApiBundle\Workflow\ImportQueueTransitions::TO_IGNORE:
          from: !php/const NewApiBundle\Enum\ImportQueueState::SUSPICIOUS
          to: !php/const NewApiBundle\Enum\ImportQueueState::TO_IGNORE
        !php/const NewApiBundle\Workflow\ImportQueueTransitions::TO_LINK:
          from: !php/const NewApiBundle\Enum\ImportQueueState::SUSPICIOUS
          to: !php/const NewApiBundle\Enum\ImportQueueState::TO_LINK
        !php/const NewApiBundle\Workflow\ImportQueueTransitions::RESET:
          from:
            - !php/const NewApiBundle\Enum\ImportQueueState::SUSPICIOUS
            - !php/const NewApiBundle\Enum\ImportQueueState::TO_CREATE
            - !php/const NewApiBundle\Enum\ImportQueueState::TO_UPDATE
            - !php/const NewApiBundle\Enum\ImportQueueState::TO_IGNORE
            - !php/const NewApiBundle\Enum\ImportQueueState::TO_LINK
          to: !php/const NewApiBundle\Enum\ImportQueueState::VALID


