version: '3.7'

networks:
    backend:
        external: false
    pma:
        external: false

services:
    php:
        # CAREFUL: "production" token is replaced in deployment script ci/deploy-docker.sh!
        image: artifactory.quanti.cz/docker/humansis-php:production
        volumes:
            - /opt/humansis/var:/var/www/html/var
            - /var/cache/humansis:/var/www/html/var/cache
            - /opt/humansis/parameters.yml:/var/www/html/app/config/parameters.yml:ro
            - /opt/humansis/jwt:/var/www/html/app/config/jwt:ro
        networks:
            - backend
        environment:
            ENVIRONMENT: prod

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8081:80
        networks:
            - pma
        volumes:
            - /opt/overrides/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        environment:
            # CAREFUL: "%env(RDS_HOSTNAME)%" token is replaced in deployment script ci/apply-env-config.sh!
            PMA_HOST: %env(RDS_HOSTNAME)%
            PMA_ABSOLUTE_URI: https://api.humansis.org/pma_yzixy37h/

    nginx:
        # CAREFUL: "production" token is replaced in deployment script ci/deploy-docker.sh!
        image: artifactory.quanti.cz/docker/humansis-nginx:production
        ports:
            - 8087:80
        depends_on:
            - php
        networks:
            - backend
