version: '3.7'

networks:
    backend:
        external: false

services:
    consumer:
        image: artifactory.quanti.cz/docker/humansis-php:stage
        volumes:
            - /opt/humansis/var:/var/www/html/var
            - /var/cache/humansis:/var/www/html/var/cache
            - /opt/humansis/parameters.yml:/var/www/html/app/config/parameters.yml:ro
        entrypoint: "php /var/www/html/bin/console messenger:consume incoming_big_data import --time-limit=3600 --limit=100 -vv"
        networks:
            - backend
        restart: always
        environment:
            ENVIRONMENT: stage
        logging:
            driver: "syslog"
            options:
                tag: docker-consumer

