version: '3.7'

networks:
    backend:
        external: false
    pma:
        external: false

volumes:
    consumercache:

services:
    php:
        # CAREFUL: "__DEV__" token is replaced in deployment script ci/deploy-docker.sh!
        image: artifactory.quanti.cz/docker/humansis-php:__DEV__
        volumes:
            - /opt/humansis/var:/var/www/html/var
            - /opt/humansis/app/Resources/translations:/var/www/html/app/Resources/translations
            - /var/cache/humansis:/var/www/html/var/cache
            - /opt/humansis/parameters.yml:/var/www/html/app/config/parameters.yml:ro
            - /opt/humansis/jwt:/var/www/html/app/config/jwt:ro
        networks:
            - backend
        environment:
            ENVIRONMENT: dev

    consumer:
        # CAREFUL: "__DEV__" token is replaced in deployment script ci/deploy-docker.sh!
        image: artifactory.quanti.cz/docker/humansis-php:__DEV__
        volumes:
            - /opt/humansis/var/sessions:/var/www/html/var/sessions
            - /opt/humansis/var/imports:/var/www/html/var/imports
            - /opt/humansis/var/logs:/var/www/html/var/logs
            - /opt/humansis/parameters.yml:/var/www/html/app/config/parameters.yml:ro
        entrypoint: "php /var/www/html/bin/console messenger:consume incoming_big_data import --time-limit=3600 --limit=100"
        networks:
            - backend
        restart: always
        environment:
            ENVIRONMENT: dev
        logging:
            driver: "syslog"
            options:
                tag: docker-consumer

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8081:80
        networks:
            - pma
        volumes:
            - /opt/overrides/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        environment:
            # CAREFUL: "%env(RDS_HOSTNAME)%" token is replaced in deployment script ci/apply-env-config.sh!
            PMA_HOST: %env(RDS_HOSTNAME)%
            # CAREFUL: "__DEV__" token is replaced in deployment script ci/deploy-docker.sh!
            PMA_ABSOLUTE_URI: https://api__DEV__.humansis.org/pma_yzixy37h/

    nginx:
        # CAREFUL: "__DEV__" token is replaced in deployment script ci/deploy-docker.sh!
        image: artifactory.quanti.cz/docker/humansis-nginx:__DEV__
        ports:
            - 8087:80
        depends_on:
            - php
        networks:
            - backend
