<?php

namespace ReportingBundle\Repository;

/**
 * ReportingDistributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportingDistributionRepository extends \Doctrine\ORM\EntityRepository
{
}
