<?php

namespace ReportingBundle\Repository;

/**
 * ReportingCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportingCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
