#!/bin/bash
cp build_info.json.dist web/build_info.json

COMMIT=`git rev-parse --short HEAD`
VER=`git describe --abbrev=0 --tags`
VERSION=`git describe --tags`
BRANCH=`git rev-parse --abbrev-ref HEAD`

sed -i -e "s|__COMMIT__|$COMMIT|g" web/build_info.json
sed -i -e "s|__VERSION_SHORT__|$VER|g" web/build_info.json
sed -i -e "s|__VERSION__|$VERSION|g" web/build_info.json
sed -i -e "s|__BRANCH__|$BRANCH|g" web/build_info.json