#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
# exec git diff-index --check --cached $against --


# ## 
# disallowed="dump var_dump"

# git diff --cached --name-status | while read x file; do
# 		echo "-------$x"
#         if [ "$x" == 'D' ]; then continue; fi
#         for word in $disallowed
#         do
#             if egrep $word $file ; then
#                 echo "ERROR: Disallowed expression \"${word}\" in file: ${file}"
#                 exit 1
#             fi
#         done
# done || exit $?

# Modify this
# LIST='list\|of\|words\|splitted\|by\|slash\|and\|pipe'
LIST="dump(\|var_dump"

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

function find_disallowed_file() {
    for FILE in $1 ; do
        # Check if the file contains one of the words in LIST
        if grep -w $LIST $FILE; then
            echo $FILE." has one of the word you don't want to commit. Please remove it"
            exit 1
        fi
    done
}

find_disallowed_file "`tree -if --noreport src | grep '.php'`"

find_disallowed_file "`tree -if --noreport tests | grep '.php'`"
