<?php

namespace ProjectBundle\Repository;
use UserBundle\Entity\User;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllOfUser(User $user)
    {
        $qb = $this->createQueryBuilder("p");
        $q = $qb->leftJoin("p.usersProject", "up")
            ->where("up.user = :user")
            ->andWhere("p.archived = 0")
            ->setParameter("user", $user);

        return $q->getQuery()->getResult();
    }
}
