framework:
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    channels: [ 'exception', 'mobile', 'import' ]
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: error
            channels: ['!event']
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        # To follow logs in real time, execute the following command:
        # `bin/console server:log -vv`
#        server_log:
#            type: server_log
#            process_psr_3_messages: false
#            host: 127.0.0.1:9911
#        # Uncommenting this section could cause serious performance degradation on Windows Docker environment
#        graylog:
#            type: service
#            id: monolog.gelf_handler
#            level: info
#            channels: ['!event', '!doctrine', '!console']
        import:
            type: stream
            path: '%kernel.logs_dir%/imports.log'
            level: info
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info

#swiftmailer:
#    delivery_addresses: ['me@example.com']

services:
    Symfony\Component\HttpKernel\Profiler\Profiler: '@profiler'

nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:8080']
