<?php

namespace DistributionBundle\Repository;

/**
 * CommodityDistributionBeneficiaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommodityDistributionBeneficiaryRepository extends \Doctrine\ORM\EntityRepository
{
}
