<?php

namespace DistributionBundle\Repository;

/**
 * DistributionDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistributionDataRepository extends \Doctrine\ORM\EntityRepository
{


    public function getLastId() {
        $qb = $this->createQueryBuilder('dd')
                   ->select("MAX(dd.id)" );
        return $qb->getQuery()->getSingleScalarResult();
    }
}
