<?php

namespace DistributionBundle\Repository;

/**
 * GeneralReliefItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneralReliefItemRepository extends \Doctrine\ORM\EntityRepository
{
}
