<?php

namespace DistributionBundle\Repository;

use DistributionBundle\Entity\Modality;

/**
 * ModalityTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModalityTypeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPublicNames(?string $modalityCode = null): array
    {
        $qbr = $this->createQueryBuilder('mt')
            ->select('mt.name')
            ->where('mt.internal = false');
        
        if ($modalityCode !== null) {
            $qbr->leftJoin('mt.modality', 'm')
                ->where('m.name = :modalityCode')
                ->setParameter('modalityCode', $modalityCode);
        }
        
        $resultArray = $qbr->getQuery()
            ->getArrayResult();

        return array_column($resultArray, 'name');
    }
}
