<?php
/**
 * AssistanceTargetBeneficiaryGeneralReliefItems
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  Humansis\UserAppApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Humansis Offline App
 *
 * This is an API documentation for Humansis Offine App.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace Humansis\UserAppApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the AssistanceTargetBeneficiaryGeneralReliefItems model.
 *
 * @package Humansis\UserAppApi\Model
 * @author  OpenAPI Generator team
 */
class AssistanceTargetBeneficiaryGeneralReliefItems 
{
        /**
     * @var int|null
     * @SerializedName("id")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $id;

    /**
     * @var string|null
     * @SerializedName("distributedAt")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $distributedAt;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->id = isset($data['id']) ? $data['id'] : null;
        $this->distributedAt = isset($data['distributedAt']) ? $data['distributedAt'] : null;
    }

    /**
     * Gets id.
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param int|null $id
     *
     * @return $this
     */
    public function setId($id = null)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets distributedAt.
     *
     * @return string|null
     */
    public function getDistributedAt()
    {
        return $this->distributedAt;
    }

    /**
     * Sets distributedAt.
     *
     * @param string|null $distributedAt
     *
     * @return $this
     */
    public function setDistributedAt($distributedAt = null)
    {
        $this->distributedAt = $distributedAt;

        return $this;
    }
}


