<?php
/**
 * InlineObject
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  Humansis\UserAppApi\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Humansis Offline App
 *
 * This is an API documentation for Humansis Offine App.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace Humansis\UserAppApi\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the InlineObject model.
 *
 * @package Humansis\UserAppApi\Model
 * @author  OpenAPI Generator team
 */
class InlineObject 
{
        /**
     * @var int[]|null
     * @SerializedName("ids")
     * @Assert\All({
     *   @Assert\Type("int")
     * })
     * @Type("array<int>")
     */
    protected $ids;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->ids = isset($data['ids']) ? $data['ids'] : null;
    }

    /**
     * Gets ids.
     *
     * @return int[]|null
     */
    public function getIds(): ?array
    {
        return $this->ids;
    }

    /**
     * Sets ids.
     *
     * @param int[]|null $ids
     *
     * @return $this
     */
    public function setIds(array $ids = null)
    {
        $this->ids = $ids;

        return $this;
    }
}


