<?php
/**
 * InlineObject2Test
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  Humansis\VendorAppApi\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Humansis Vendor App
 *
 * This is an API documentation for Humansis Vendor App.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace Humansis\VendorAppApi\Model;

use PHPUnit\Framework\TestCase;

/**
 * InlineObject2Test Class Doc Comment
 *
 * @category    Class */
// * @description InlineObject2
/**
 * @package     Humansis\VendorAppApi\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 */
class InlineObject2Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineObject2"
     */
    public function testInlineObject2()
    {
        $testInlineObject2 = new InlineObject2();
    }

    /**
     * Test attribute "products"
     */
    public function testPropertyProducts()
    {
    }

    /**
     * Test attribute "createdAt"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "vendorId"
     */
    public function testPropertyVendorId()
    {
    }

    /**
     * Test attribute "beneficiaryId"
     */
    public function testPropertyBeneficiaryId()
    {
    }

    /**
     * Test attribute "assistanceId"
     */
    public function testPropertyAssistanceId()
    {
    }

    /**
     * Test attribute "balanceBefore"
     */
    public function testPropertyBalanceBefore()
    {
    }

    /**
     * Test attribute "balanceAfter"
     */
    public function testPropertyBalanceAfter()
    {
    }
}
