<?php
/**
 * SmartcardRedemptionCandidateTest
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  Humansis\VendorAppApi\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Humansis Vendor App
 *
 * This is an API documentation for Humansis Vendor App.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace Humansis\VendorAppApi\Model;

use PHPUnit\Framework\TestCase;

/**
 * SmartcardRedemptionCandidateTest Class Doc Comment
 *
 * @category    Class */
// * @description SmartcardRedemptionCandidate
/**
 * @package     Humansis\VendorAppApi\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 */
class SmartcardRedemptionCandidateTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SmartcardRedemptionCandidate"
     */
    public function testSmartcardRedemptionCandidate()
    {
        $testSmartcardRedemptionCandidate = new SmartcardRedemptionCandidate();
    }

    /**
     * Test attribute "projectId"
     */
    public function testPropertyProjectId()
    {
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }
}
