sentry:
    #todo set proper project dns
    dsn: "https://7ff5069624384df8bf3d303b551f8453@o1378753.ingest.sentry.io/6690862"
    messenger:
        enabled: true # flushes Sentry messages at the end of each message handling
        capture_soft_fails: true # captures exceptions marked for retry too
    options:
        environment: '%kernel.environment%'
