services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ProjectBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: [ 'app.controller' ]

#######################################################################################
##                                       CRUD                                        ##
#######################################################################################

    project.project_service:
        class: ProjectBundle\Utils\ProjectService
        arguments: ['@doctrine.orm.entity_manager', '@serializer', '@validator' , '@service_container']
        public: true

    project.donor_service:
        class: ProjectBundle\Utils\DonorService
        arguments: ['@doctrine.orm.entity_manager', '@serializer', '@validator', '@service_container']
        public: true

    project.sector_service:
        class: ProjectBundle\Utils\SectorService
        arguments: ['@doctrine.orm.entity_manager', '@serializer', '@validator']
        public: true

    ProjectBundle\Mapper\ProjectMapper:
        arguments:
            - '@ProjectBundle\Mapper\DonorMapper'
            - '@ProjectBundle\Mapper\SectorMapper'
            - '@BeneficiaryBundle\Mapper\AssistanceMapper'
            - '@beneficiary.repository'
            - '@project.sector_service'
        public: true

    ProjectBundle\Mapper\DonorMapper:
        public: true

    ProjectBundle\Mapper\SectorMapper:
        arguments:
            - '@translator'
        public: true

    project.sector_mapper:
        class: ProjectBundle\Mapper\SectorMapper
        arguments: []
        public: true
