services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ProjectBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: [ 'app.controller' ]

#######################################################################################
##                                       CRUD                                        ##
#######################################################################################

    project.project_service:
        alias: ProjectBundle\Utils\ProjectService
        public: true

    ProjectBundle\Utils\ProjectService:
        arguments: ['@doctrine.orm.entity_manager', '@service_container']

    project.donor_service:
        alias: ProjectBundle\Utils\DonorService
        public: true

    ProjectBundle\Utils\DonorService:
        arguments: ['@doctrine.orm.entity_manager', '@service_container']

    project.sector_service:
        alias: ProjectBundle\Utils\SectorService
        public: true

    ProjectBundle\Utils\SectorService:

    ProjectBundle\Mapper\ProjectMapper:
        arguments:
            - '@ProjectBundle\Mapper\DonorMapper'
            - '@ProjectBundle\Mapper\SectorMapper'
            - '@NewApiBundle\MapperDeprecated\AssistanceMapper'
            - '@beneficiary.repository'
            - '@project.sector_service'
        public: true

    ProjectBundle\Mapper\DonorMapper:
        public: true

    ProjectBundle\Mapper\SectorMapper:
        arguments:
            - '@translator'
        public: true

    project.sector_mapper:
        class: ProjectBundle\Mapper\SectorMapper
        arguments: []
        public: true

    ProjectBundle\Repository\ProjectRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        calls:
            - injectSecurity: [ "@security.authorization_checker"]
        arguments:
            - ProjectBundle\Entity\Project
        public: true
